Dockerfile
cloudbuild.yaml

Add dockerfile and cloudbuild

---

apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po

Sets the string to display from POA to cGLD

Update to cGLD

---

README.md

Updated badge to our fork.
Pending to decide if we should add additional badges.

Updated Badges

---

apps/block_scout_web/assets/css/theme/_celo_variables.scss

Closes https://github.com/celo-org/celo-monorepo/issues/1900

Improve header input visualization

---

apps/explorer/lib/explorer/chain/events/publisher.ex

Quick fix for https://github.com/celo-org/celo-monorepo/issues/1912
Next can check if it's already fixed properly in upstream.
Of course have to also check this actually fixes the problem we are having.

Restrict payload size

---

apps/block_scout_web/lib/block_scout_web/controllers/address_celo_controller.ex
apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
apps/block_scout_web/lib/block_scout_web/templates/address_celo/index.html.eex
apps/block_scout_web/lib/block_scout_web/views/address_celo_view.ex
apps/block_scout_web/lib/block_scout_web/views/address_view.ex
apps/block_scout_web/lib/block_scout_web/web_router.ex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
apps/explorer/lib/explorer/chain.ex
apps/explorer/lib/explorer/chain/address.ex

Shows Celo related info in a new tab.
Info in the validator and validator groups table still has to be included.

Added a tab to the addresses to show Celo related information

---

apps/explorer/lib/explorer/chain.ex
apps/explorer/priv/repo/migrations/20191114104543_create_leaderboard.exs

Added reading old values of usd and gold to the query. Also added attestation multiplier.

Leaderboard query improvements

---

apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
apps/explorer/lib/explorer/celo/account_reader.ex
apps/explorer/lib/explorer/chain.ex
apps/indexer/config/config.exs
apps/indexer/config/test.exs
apps/indexer/lib/indexer/block/fetcher.ex
apps/indexer/lib/indexer/transform/addresses.ex

Updates the gold token each time the native coin is updated. 
Also fixes a problem with "Celo info" tab always appearing when in "Blocks validated" tab.
See issue https://github.com/celo-org/celo-monorepo/issues/1988
Got a deadlock error at one phase, going to need more testing to find out if that is a problem.

Reading gold token

---

apps/block_scout_web/lib/block_scout_web/templates/address_celo/index.html.eex

Fixes https://github.com/celo-org/celo-monorepo/issues/2044

Changed account url into link

---

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs

*Why we should merge these changes.  If using GitHub keywords to close [issues](https://github.com/poanetwork/blockscout/issues), this is optional as the motivation can be read on the issue page.*
*Things you added that don't break anything.  Regression tests for Bug Fixes count as Enhancements.*
*Things you changed that fix bugs.  If a fixes a bug, but in so doing adds a new requirement, removes code, or requires a database reset and reindex, the breaking part of the change should be added to Incompatible Changes below also.*
*Things you broke while doing Enhancements and Bug Fixes.  Breaking changes include (1) adding new requirements and (2) removing code.  Renaming …

Changing format to fix test

---

apps/block_scout_web/lib/block_scout_web/templates/address_celo/index.html.eex

Quick fix for an error when a validator has a signer that is not yet in the database.

Fixing internal server error with 0xCAd07eBF3c922bfe1292d4fbfcE015a934e520B9

---

apps/block_scout_web/lib/block_scout_web/controllers/block_controller.ex
apps/block_scout_web/lib/block_scout_web/controllers/block_transaction_controller.ex
apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
apps/block_scout_web/lib/block_scout_web/notifier.ex
apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex
apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex
apps/block_scout_web/lib/block_scout_web/templates/chain/_block.html.eex
apps/block_scout_web/lib/block_scout_web/views/address_view.ex
apps/block_scout_web/lib/block_scout_web/views/block_view.ex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
apps/block_scout_web/test/block_scout_web/controllers/block_transaction_controller_test.exs
apps/explorer/lib/explorer/chain/block.ex
apps/explorer/lib/explorer/chain/cache/blocks.ex
apps/explorer/lib/explorer/chain/celo_account.ex
apps/explorer/lib/explorer/chain/import/runner/address/names.ex
apps/explorer/lib/explorer/chain/import/stage/address_referencing.ex
apps/explorer/test/explorer/chain/cache/blocks_test.exs
apps/indexer/lib/indexer/block/fetcher.ex
apps/indexer/lib/indexer/transform/celo_accounts.ex

Showing account names in the blocks they have validated and some other places.

Adding account names

---

apps/block_scout_web/config/config.exs
apps/block_scout_web/mix.exs
apps/ethereum_jsonrpc/config/config.exs
apps/ethereum_jsonrpc/mix.exs
apps/explorer/config/config.exs
apps/explorer/mix.exs
apps/indexer/config/config.exs
apps/indexer/mix.exs
config/config.exs
docker/Dockerfile
mix.lock

Solves https://github.com/celo-org/celo-monorepo/issues/1921
Needs an additional path on helm package to filter the expression `iex(1)> `.

Logs format json

---

apps/block_scout_web/lib/block_scout_web/resolvers/celo_util.ex
apps/block_scout_web/lib/block_scout_web/resolvers/celo_validator.ex
apps/block_scout_web/lib/block_scout_web/schema.ex
apps/block_scout_web/lib/block_scout_web/schema/types.ex
apps/explorer/lib/explorer/celo/account_reader.ex
apps/explorer/lib/explorer/chain.ex
apps/explorer/lib/explorer/chain/celo_account.ex
apps/explorer/lib/explorer/chain/celo_validator_group.ex
apps/explorer/lib/explorer/chain/celo_validator_history.ex
apps/explorer/priv/repo/migrations/20191011140922_create_celo_account.exs
apps/indexer/lib/indexer/fetcher/celo_validator.ex
apps/indexer/lib/indexer/fetcher/celo_validator_history.ex
apps/indexer/lib/indexer/transform/celo_accounts.ex

Added a field for votes into validator group table.
Added link in account to usd token amount.
Added for validators the last block they were elected at.

Group votes and other additions

---

apps/block_scout_web/assets/__tests__/lib/currency.js
apps/block_scout_web/assets/js/lib/currency.js
apps/block_scout_web/assets/js/lib/market_history_chart.js
apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po

Changed cUSD back to USD.
Modified the chart on the front page.

Exchange rate related UI fixes

---

apps/block_scout_web/lib/block_scout_web/views/address_view.ex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
apps/explorer/lib/explorer/chain.ex
apps/explorer/lib/explorer/chain/celo_signers.ex
apps/explorer/priv/repo/migrations/20191011140922_create_celo_account.exs

Merged the previous one too early, Celo info page was broken for signers. Also adding few extra data items now.

Celo info page for validator signers

---

apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
apps/block_scout_web/lib/block_scout_web/templates/address_celo/index.html.eex
apps/block_scout_web/lib/block_scout_web/templates/address_decompiled_contract/index.html.eex
apps/block_scout_web/lib/block_scout_web/views/address_view.ex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po

There were still some visibility issues left, at least for example the tab link showed up when in Code tab.
Also added group commission and votes to the info page.

Celo info page visibility fix

---

apps/block_scout_web/lib/block_scout_web/resolvers/celo_util.ex
apps/block_scout_web/lib/block_scout_web/resolvers/celo_validator.ex
apps/explorer/lib/explorer/chain/celo_account.ex

Also removed spurious GraphQL error messages

Added handling event for vote rewards

---

config/config.exs

Default logging level to info

---

apps/explorer/lib/explorer/celo/account_reader.ex
apps/explorer/lib/explorer/chain/import/runner/celo_validator_groups.ex
apps/indexer/lib/indexer/fetcher/celo_validator_history.ex

Just a simple change so that the downtime is assigned to correct blocks.

Changed downtime to correct blocks

---

apps/block_scout_web/lib/block_scout_web/views/block_signers_view.ex
apps/block_scout_web/lib/block_scout_web/views/block_view.ex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po

There were some errors when a validator didn't have a name.

Handling accounts with no name

---

apps/indexer/lib/indexer/transform/celo_accounts.ex

Should fix https://github.com/celo-org/celo-monorepo/issues/2765

Fixing sync issue

---

apps/block_scout_web/lib/block_scout_web/templates/address_celo/index.html.eex
apps/explorer/lib/explorer/celo/account_reader.ex
apps/explorer/lib/explorer/chain.ex
apps/explorer/lib/explorer/chain/address.ex
apps/explorer/lib/explorer/chain/celo_attestation_stats.ex
apps/explorer/lib/explorer/chain/import/runner/celo_voter_rewards.ex
apps/explorer/lib/explorer/graphql.ex
apps/explorer/priv/repo/migrations/20200211130856_create_celo_voter_rewards_view.exs
apps/indexer/config/config.exs
apps/indexer/lib/indexer/block/catchup/bound_interval_supervisor.ex
apps/indexer/lib/indexer/memory/monitor.ex

There were problems with attestations stats, so changed it to materialized view.

Attestations as materialized view

---

apps/explorer/lib/explorer/chain/celo_validator.ex

`CeloValidatorGroups` query was broken.

Fixing a query

---

apps/explorer/lib/explorer/etherscan/logs.ex

Perhaps something went wrong when merging this from upstream.

Logs query fix

---

apps/block_scout_web/config/config.exs
apps/block_scout_web/config/test.exs
apps/block_scout_web/lib/block_scout_web/chain.ex
apps/block_scout_web/lib/block_scout_web/router.ex
apps/explorer/lib/explorer/celo/account_reader.ex
apps/explorer/lib/explorer/chain.ex
apps/explorer/lib/explorer/chain/celo_account.ex
apps/explorer/lib/explorer/chain/celo_params.ex
apps/explorer/lib/explorer/chain/import/runner/celo_params.ex
apps/explorer/lib/explorer/graphql.ex
apps/explorer/priv/repo/migrations/20200420092751_add_address_params.exs
apps/indexer/lib/indexer/block/fetcher.ex
apps/indexer/lib/indexer/transform/celo_accounts.ex

Fixed getting prices from oracles.
Also can now search by contract name. Note that to get for example Reserve contract, you need to search for ReserveProxy.
Added GraphQL complexity as env variable, also fixes to token transactions.

Some fixes

---

apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po

Removed references to POA network.

Footer changes

---

apps/explorer/lib/explorer/chain.ex

There are still some problems with the user interface, for some reason it doesn't report errors etc.

Fixing contract verification

---

apps/explorer/lib/explorer/chain.ex

Hopefully this is enough to fix it.

Fixing addresses with claimed domains

---

apps/block_scout_web/lib/block_scout_web/controllers/address_contract_controller.ex
apps/block_scout_web/lib/block_scout_web/controllers/address_read_contract_controller.ex
apps/block_scout_web/lib/block_scout_web/templates/chain/_metatags.html.eex
apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
apps/block_scout_web/lib/block_scout_web/views/chain_view.ex
apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
apps/explorer/package-lock.json
docker/Dockerfile

Following fixes
* Fixes issues with tabs https://github.com/celo-org/celo-monorepo/issues/3687
* Removes the price graph
* Fixes the title so that it won't be "Celo Celo explorer"

Few web fixes

---

apps/explorer/lib/explorer/chain/celo_account.ex

These events were changed recently (actually there was only one event before).
Fixes https://github.com/celo-org/celo-monorepo/issues/3684

Adding vote revoked events

---

apps/block_scout_web/lib/block_scout_web/templates/address_celo/index.html.eex
apps/block_scout_web/lib/block_scout_web/views/address_celo_view.ex
apps/explorer/config/config.exs
apps/explorer/lib/explorer/application.ex
apps/explorer/lib/explorer/celo/account_reader.ex
apps/explorer/lib/explorer/celo/signer_cache.ex
apps/explorer/lib/explorer/celo/util.ex
apps/indexer/lib/indexer/block/fetcher.ex
apps/indexer/lib/indexer/fetcher/internal_transaction.ex
apps/indexer/lib/indexer/transform/address_coin_balances.ex

Reading the current signers is slow, and they don't change during epochs. Added a cache to save these for each epoch.

Caching epoch signers

---

apps/block_scout_web/lib/block_scout_web/templates/address_celo/index.html.eex
apps/block_scout_web/lib/block_scout_web/views/address_celo_view.ex

Instead of -1 do show not accepted. Also the members are now sorted.

Changing how membership is shown

---

apps/block_scout_web/lib/block_scout_web/templates/address_celo/index.html.eex
apps/block_scout_web/lib/block_scout_web/views/address_celo_view.ex
apps/indexer/lib/indexer/block/fetcher.ex
apps/indexer/lib/indexer/transform/address_coin_balances.ex

Looks like some transfers were missed, this should fix the problem.

Updating balances from cGLD transfers

---

apps/block_scout_web/lib/block_scout_web/controllers/address_read_contract_controller.ex
apps/block_scout_web/lib/block_scout_web/controllers/transaction_internal_transaction_controller.ex
apps/block_scout_web/lib/block_scout_web/controllers/transaction_log_controller.ex
apps/explorer/lib/explorer/chain.ex
apps/explorer/lib/explorer/chain/address.ex
apps/explorer/lib/explorer/chain/log.ex
apps/explorer/lib/explorer/chain/proxy_contract.ex
apps/explorer/lib/explorer/chain/transaction.ex
apps/explorer/priv/repo/migrations/20200430080102_change_celo_voter_rewards_view.exs

Changed reward ratio to use a formula where it cannot be over 100%, 
Transactions and logs for proxied contract should now be decoded in more case.

Change reward ratio, proxy contract improvements

---

apps/explorer/lib/explorer/celo/account_reader.ex
apps/explorer/lib/explorer/chain.ex
apps/explorer/priv/repo/migrations/20200430080102_change_celo_voter_rewards_view.exs
apps/indexer/lib/indexer/block/fetcher.ex

Looks like there were some problems, hopefully fixed now. Tested with mainnet.

Fixes to rewards ratio

---

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex

Probably something Celo related is messing up the traces, got a negative value.

"Internal server error" when getting raw trace

---

.circleci/config.yml
apps/explorer/lib/explorer/chain/celo_account.ex
apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs

Needed to keep track of group commissions.

Commission update event

---

apps/block_scout_web/config/config.exs

Increased default complexity

---

apps/block_scout_web/config/config.exs
apps/explorer/priv/repo/migrations/20200622122342_create_internal_tx_index.exs

Increased GraphQL limit.
Added an index for a query that became slow.

Some settings needed by wallet

---

apps/explorer/lib/explorer/chain/import/runner/tokens.ex

Trying to fix overwriting token metadata with empty data.

Changing updating tokens

---

apps/explorer/lib/explorer/chain/import/runner/tokens.ex
apps/explorer/test/explorer/chain/import/runner/tokens_test.exs

Github was down so the tests were not running.

Fixing tests

---

apps/block_scout_web/lib/block_scout_web/schema/types.ex
apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/_token_transfer.html.eex
apps/block_scout_web/lib/block_scout_web/templates/transaction/_token_transfer.html.eex
apps/block_scout_web/lib/block_scout_web/templates/transaction_token_transfer/_token_transfer.html.eex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
apps/explorer/lib/explorer/chain/token_transfer.ex
apps/explorer/lib/explorer/graphql.ex
apps/explorer/priv/repo/migrations/20200603083313_transfer_comment.exs
apps/indexer/lib/indexer/transform/token_transfers.ex
apps/indexer/test/indexer/transform/token_transfers_test.exs

Adding support for transfer comments.

Transfer comment

---

apps/block_scout_web/lib/block_scout_web/views/address_celo_view.ex

should fix this page https://rc1-blockscout.celo-testnet.org/address/0x1a4f4fd50e236056a188dd58fcc937e324f35141/celo

Fix celo info error

---

apps/explorer/lib/explorer/chain.ex
apps/explorer/lib/explorer/chain/token.ex
apps/indexer/config/config.exs
apps/indexer/lib/indexer/buffered_task.ex
apps/indexer/lib/indexer/fetcher/internal_transaction.ex
apps/indexer/lib/indexer/fetcher/token_updater.ex

It only updated when blockscout was started up.

Update token metadata periodically

---

apps/block_scout_web/config/config.exs
apps/block_scout_web/lib/block_scout_web/router.ex
apps/explorer/lib/explorer/chain/events/publisher.ex

Make wobserver optional

---

apps/block_scout_web/lib/block_scout_web/controllers/transaction_raw_trace_controller.ex
apps/block_scout_web/lib/block_scout_web/controllers/transaction_token_transfer_controller.ex
apps/indexer/lib/indexer/buffered_task.ex

Fixing decoding TX inputs

---

apps/indexer/lib/indexer/block/catchup/bound_interval_supervisor.ex

Refreshes materialized views 10x less than before.

Refresh materialized views less

---

apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
apps/explorer/config/config.exs

Since the current market cap is not taking into account actual circulating supply, it’s a little off. Correct calculation can be implemented later.

Removed market cap

---

apps/explorer/lib/explorer/chain/celo_attestation.ex
apps/explorer/lib/explorer/chain/import/runner/celo_attestations.ex
apps/explorer/lib/explorer/chain/import/stage/address_referencing.ex
apps/explorer/priv/repo/migrations/20200610113914_add_celo_attestations.exs
apps/indexer/lib/indexer/block/fetcher.ex
apps/indexer/lib/indexer/transform/attestation.ex

*Why we should merge these changes.  If using GitHub keywords to close [issues](https://github.com/poanetwork/blockscout/issues), this is optional as the motivation can be read on the issue page.*
*Things you added that don't break anything.  Regression tests for Bug Fixes count as Enhancements.*
*Things you changed that fix bugs.  If a fixes a bug, but in so doing adds a new requirement, removes code, or requires a database reset and reindex, the breaking part of the change should be added to Incompatible Changes below also.*
*Things you broke while doing Enhancements and Bug Fixes.  Breaking changes include (1) adding new requirements and (2) removing code.  Renaming …

fixed it so that it compiles

---

CHANGELOG.md
apps/explorer/priv/repo/migrations/20200421102450_pending_txs.exs

Merging https://github.com/poanetwork/blockscout/pull/3077 from upstream as a pre-requisite for https://github.com/celo-org/blockscout/pull/139

Finally speedup pending tx list

---

apps/block_scout_web/lib/block_scout_web/api_router.ex
apps/block_scout_web/lib/block_scout_web/controllers/api/v1/health_controller.ex
apps/explorer/lib/health.ex
apps/indexer/lib/indexer/health/plug.ex

Adds a health check to the web app that would be used as k8s liveness/readiness probe.

Added liveness probe for the web app

---

apps/block_scout_web/assets/js/pages/survey_banner.js

Changed our minds about how we wanted this banner to behave.  Would like dismissal to be permanent.

changed sessionStorage to localStorage

---

cloudbuild.yaml
docker/Dockerfile

*Why we should merge these changes.  If using GitHub keywords to close [issues](https://github.com/poanetwork/blockscout/issues), this is optional as the motivation can be read on the issue page.*
*Things you added that don't break anything.  Regression tests for Bug Fixes count as Enhancements.*
*Things you changed that fix bugs.  If a fixes a bug, but in so doing adds a new requirement, removes code, or requires a database reset and reindex, the breaking part of the change should be added to Incompatible Changes below also.*
*Things you broke while doing Enhancements and Bug Fixes.  Breaking changes include (1) adding new requirements and (2) removing code.  Renaming …

Jcortejoso/merge 2021.2

---

apps/block_scout_web/config/prod.exs
apps/indexer/config/config.exs
apps/indexer/lib/indexer/block/fetcher.ex

Looks like there was one thing that I had removed when testing, and then forgot to put it back. Hopefully that resolves the issue here https://github.com/celo-org/blockscout/issues/213.
Also changed the env variable name for health check port to that it's easier to run locally.

Changed adding tokens

---

apps/explorer/lib/explorer/chain.ex
apps/explorer/lib/explorer/chain/import/runner/blocks.ex
apps/indexer/config/dev.exs
apps/indexer/config/prod.exs
apps/indexer/lib/indexer/block/realtime/fetcher.ex
apps/indexer/lib/indexer/pending_transactions_sanitizer.ex
apps/indexer/lib/indexer/supervisor.ex
config/config.exs

WIP.
Fixes https://github.com/celo-org/blockscout/issues/229

Pending transaction sanitizer

---

apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po

Updated token name

---

apps/indexer/lib/indexer/block/fetcher.ex

Changed so that works when system contracts are not deployed.

Working without system contracts

---

apps/block_scout_web/lib/block_scout_web/schema/types.ex

Fixed the field type

---

apps/block_scout_web/lib/block_scout_web/schema.ex

Solve problem querying graphql transfers.
Close #314

Fix query error return

---

apps/block_scout_web/assets/package-lock.json
apps/block_scout_web/assets/package.json
apps/explorer/package-lock.json
apps/explorer/package.json

Dependencies updates from Snyk bot.

Snyk bot dependencies update

---

apps/block_scout_web/assets/package-lock.json
apps/block_scout_web/assets/package.json

Snyk dependencies update 3

---

apps/block_scout_web/assets/package-lock.json
apps/block_scout_web/assets/package.json

Snyk upgrades 4

---

apps/block_scout_web/config/config.exs
apps/block_scout_web/lib/block_scout_web/application.ex
apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex

The error metric in web wasn't incremented although errors were observed. This PR makes sure that the logger backend responsible for incrementing the counter is started.

Make sure logger backend is added to web application

---

apps/explorer/lib/explorer/graphql.ex

This is related with https://github.com/celo-org/data-services/issues/31
Close https://github.com/celo-org/data-services/issues/31

Update method to work similar to celoTransfers

---

apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
apps/block_scout_web/lib/block_scout_web/views/wei_helpers.ex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
apps/block_scout_web/test/block_scout_web/views/transaction_view_test.exs
apps/explorer/lib/explorer/chain/transaction.ex

Updates view helper functions to display gas fees taking the gas fee currency into account.
Before:
After:
Renames some functions to be more precise on what they are doing.
Added a test to make sure it produces the correct output.
- Fixes https://github.com/celo-org/data-services/issues/42
Yes, if currency is not passed, it falls back to the old behavior.

Displaying TX fee with correct token symbol

---

apps/block_scout_web/lib/block_scout_web/views/address_celo_view.ex

Close https://github.com/celo-org/data-services/issues/23
Close https://github.com/celo-org/data-services/issues/19
Both related with a problem calculating the validators in a group

Fix issue with validator non part of the group2

---

apps/block_scout_web/assets/package-lock.json
apps/block_scout_web/assets/package.json
load-testing/package-lock.json
load-testing/package.json

Dependencies upgrade: 
- redux 4.0.5 -> 4.1.0
- analytics 0.7.13 -> 0.7.14
- csv-parse 4.16.0 -> 4.16.2
- artillery 1.7.7 -> 1.7.8

W40 Snyk updates

---

.github/workflows/config.yml
apps/block_scout_web/assets/css/components/_card.scss
apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
apps/indexer/lib/indexer/fetcher/internal_transaction.ex

More small tweaks
* Fixes an issue with the plus button on read contract button being invisible
* see https://explorer.celo.org/address/0x5b067A64025A871e668Ca7C5B94177Bf0Ded9940/read-contract
* Adjust log message for "Block not indexed correctly" to give more context and info
* Change token dropdown label from "Ether" to "CELO"
* Expanded the `db_check` function to have multiple clauses 
* Removed a duplicate logging function for errors in handling internal transaction fetches
* "Translation keys missing" ci test needed tweaks again, it was failing when nothing had changed
* CI tests

Adjust log message, fix translation, css fix and a small refactor

---

apps/block_scout_web/lib/block_scout_web/resolvers/token_transfer_tx.ex
apps/block_scout_web/lib/block_scout_web/schema.ex
apps/explorer/lib/explorer/graphql.ex

Fix issue retrieving tokens that are not only celo specific.
Alfaores
- Relates to #[issue number here]
- Fixes #[issue number here]

Remove filter by contract names

---

apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po

Fix error in the balance coin name
No

Fix typo in the label

---

apps/indexer/lib/indexer/fetcher/internal_transaction.ex
apps/indexer/test/indexer/block/fetcher_test.exs

Fix non updated coin balances.
No
Done
- Fixes #473 

Fix issue with wrong updated token balances

---

apps/block_scout_web/assets/js/pages/verification_form.js
apps/block_scout_web/lib/block_scout_web/etherscan.ex
apps/block_scout_web/lib/block_scout_web/notifier.ex
apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_common_fields/_compiler_field.html.eex
apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_common_fields/_constructor_args.html.eex
apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_common_fields/_contract_address_field.html.eex
apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_common_fields/_contract_name_field.html.eex
apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_vyper/new.html.eex
apps/block_scout_web/lib/block_scout_web/views/address_contract_verification_common_fields_view.ex
apps/block_scout_web/lib/block_scout_web/views/changeset_view.ex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
apps/explorer/lib/explorer/chain/events/db_sender.ex
apps/explorer/lib/explorer/chain/events/publisher.ex
apps/explorer/lib/explorer/smart_contract/vyper/publisher.ex

This PR improves vyper smart contracts verification UX:
- fixes an issue blocking communication between the backend and the frontend when the payload of the broadcasted message exceeds 7.5K
- changes the way form submission and validation is handled
- minor UX fixes that introduce standard form interactions on form submission like disabling fields etc.
It's one of multiple improvements in contract verification experience that would be merged into the dedicated [contract-verification-ux-improvements](https://github.com/celo-org/blockscout/tree/contract-verification-ux-improvements) branch, tested together and deployed as a whole.
Fixes …

Vyper verification UX improvements

---

apps/block_scout_web/assets/css/app.scss
apps/block_scout_web/assets/css/components/_datastudio.scss
apps/block_scout_web/assets/js/pages/stats.js
apps/block_scout_web/assets/package-lock.json
apps/block_scout_web/assets/webpack.config.js
apps/block_scout_web/lib/block_scout_web/templates/stats/index.html.eex
apps/block_scout_web/lib/block_scout_web/views/stats_view.ex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po

Update dashboard iframe to be more responsive
Tested
- Fixes https://github.com/celo-org/data-services/issues/171

Stats responsive

---

apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po

Update apps menu to align items.
Tested

Move columns to rows

---

apps/explorer/priv/repo/migrations/20220614130531_add_address_current_token_balances_ordering_index.exs

- Relates to https://github.com/celo-org/data-services/issues/308

Fix token holder query

---

apps/block_scout_web/assets/js/pages/token_counters.js
apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/index.html.eex

- Fixes [#[308]](https://github.com/celo-org/data-services/issues/308)

Disable token holder refreshing

---

apps/block_scout_web/lib/block_scout_web/web_router.ex

Fix some routes that were not showing the not found error properly.
In blockscoutstagingrc1
- Fixes #https://github.com/celo-org/data-services/issues/312

Fix error using show method

---

CHANGELOG.md
apps/explorer/lib/explorer/chain.ex

This PR merges fix for slow block gap detection query.

Upstream merge: fix block gap detection query

---

apps/block_scout_web/lib/block_scout_web/views/block_view.ex
apps/block_scout_web/test/block_scout_web/features/viewing_blocks_test.exs
apps/block_scout_web/test/block_scout_web/views/block_view_test.exs
apps/explorer/lib/explorer/chain/block.ex

The purpose of this PR is not show the status reorg when some blocks are being fetched because that status is not real in celo network.
- Close https://github.com/celo-org/data-services/issues/240

Change reorg type

---

apps/block_scout_web/config/config.exs
apps/block_scout_web/lib/block_scout_web/schema/types.ex
apps/explorer/lib/explorer/graphql.ex
load-testing/schema.gql

This PR exposes token type field to be used in GraphQL queries.
- Fixes https://github.com/celo-org/data-services/issues/327

Expose token type in graphQL query

---

apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
apps/block_scout_web/lib/block_scout_web/views/address_view.ex
apps/explorer/lib/explorer/chain.ex

Only show the downtime tab when apply.
Tested
- Close https://github.com/celo-org/data-services/issues/77

Downtime only for validators

---

apps/block_scout_web/lib/block_scout_web/templates/address_token/_tokens.html.eex

Fixes issue where wrong token type was being displayed.
- Fixes https://github.com/celo-org/data-services/issues/409

Fix wrong token type displayed on address tokens page

---

apps/block_scout_web/lib/block_scout_web/controllers/block_epoch_transaction_controller.ex
apps/block_scout_web/lib/block_scout_web/templates/epoch_transaction/_epoch_tile.html.eex
apps/explorer/lib/explorer/celo/epoch_util.ex
apps/explorer/lib/explorer/celo/events/celo_contract_events/common/transfer_event.ex
apps/explorer/lib/explorer/chain/celo/celo_epoch_rewards.ex
apps/explorer/priv/repo/migrations/20220811071547_add_reserve_bolster_to_epoch_rewards.exs
apps/indexer/lib/indexer/fetcher/celo_epoch_data.ex
apps/indexer/test/indexer/fetcher/celo_epoch_data_test.exs

Shows reserve bolster transaction for epoch blocks.
Fixes https://github.com/celo-org/data-services/issues/404

Show reserve bolster transaction

---

apps/block_scout_web/lib/block_scout_web/etherscan.ex

Updates the explorer link in the documentation.
Changes the verb used in one of the endpoints from "mined" to "validated".
Locally.
- Fixes https://github.com/celo-org/data-services/issues/355
Yes.

Changed URL to point to explorer

---

apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex

Updating tooltip to correct description
[Before](https://user-images.githubusercontent.com/97618969/184718743-979174a2-0bea-4e6b-a475-99ad802a0522.png)
[After](https://user-images.githubusercontent.com/97618969/184717354-96dd095c-f55b-48b1-aa38-6c1910e61524.png)

updating tooltip

---

apps/block_scout_web/lib/block_scout_web/controllers/block_epoch_transaction_controller.ex
apps/block_scout_web/lib/block_scout_web/templates/epoch_transaction/_epoch_tile.html.eex

Fixes https://github.com/celo-org/data-services/issues/464

Fix missing address error

---

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/rpc_translator.ex

Returns 404 instead of 500 when request path is unknown in an api call.
e.g. 
https://explorer.celo.org/api/api?action=tokentx&contractaddress=0xD8763CBa276a3738E6DE85b4b3bF5FDed6D6cA73&module=account&address=0xfbf2eb650a2cf68887c4b4406e51852d4f1d0177&startblock=15186192&endblock=999999999&sort=asc&page=1&offset=50&apikey=sdf
will return 404 (as `api/api` is not a valid request path) whereas previously it would return a generic 500 error
* none
* tested locally 
- Fixes https://github.com/celo-org/data-services/issues/492

Return 404 for unknown request path.

---

apps/block_scout_web/lib/block_scout_web/views/epoch_transaction_view.ex
apps/block_scout_web/test/block_scout_web/views/epoch_transaction_view_test.exs

Fixes https://github.com/celo-org/data-services/issues/489

Epoch rewards: better rounding

---

apps/explorer/lib/explorer/repo.ex

Adds url parsing to the read replica repo.
No.

Parse db url for replica

---

apps/block_scout_web/assets/css/components/_campaign_banner.scss
apps/block_scout_web/assets/js/lib/campaign_banner.js
apps/block_scout_web/assets/webpack.config.js
apps/block_scout_web/lib/block_scout_web/templates/layout/_campaign_banner.html.eex

Fixes https://github.com/celo-org/data-services/issues/498
Demo: 
https://user-images.githubusercontent.com/312010/192219950-9daff4a5-15bf-4491-9f74-279596689eb6.mov

Banner UI: JS to control closing and persisting the choice of user

---

apps/block_scout_web/lib/block_scout_web/web_router.ex

Fixes https://github.com/celo-org/data-services/issues/500

Not found error for epoch transactions in /block route

---

apps/explorer/lib/explorer/chain/celo/celo_election_rewards.ex
apps/explorer/lib/explorer/chain/celo_account_epoch.ex
apps/explorer/lib/explorer/chain/import/runner/celo_account_epoch.ex
apps/explorer/priv/repo/migrations/20220928075832_add_block_number_to_celo_accounts_epochs.exs
apps/explorer/priv/repo/migrations/20220928075913_add_aggregation_index_to_celo_election_rewards.exs
apps/indexer/lib/indexer/fetcher/celo_epoch_data.ex
apps/indexer/test/indexer/fetcher/celo/celo_epoch_data_test.exs

Fixes https://github.com/celo-org/data-services/issues/501

Optimise fetching epoch block transactions

---

apps/explorer/lib/explorer/chain/celo/celo_epoch_rewards.ex
apps/explorer/priv/repo/migrations/20220928095425_reset_reserve_bolster.exs
apps/indexer/test/indexer/fetcher/celo/celo_epoch_data_test.exs

Fixes https://github.com/celo-org/data-services/issues/502

Fix reserve bolster fetching

---

apps/block_scout_web/assets/css/components/_campaign_banner.scss
apps/block_scout_web/assets/css/main-page.scss
apps/block_scout_web/assets/js/lib/campaign_banner.js
apps/block_scout_web/config/config.exs
apps/block_scout_web/lib/block_scout_web/application.ex
apps/block_scout_web/lib/block_scout_web/campaign_banner.ex
apps/block_scout_web/lib/block_scout_web/templates/layout/_campaign_banner.html.eex
apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex

Fixes https://github.com/celo-org/data-services/issues/497

Backend component to fetch and cache data

---

apps/block_scout_web/lib/block_scout_web/templates/layout/_campaign_banner.html.eex

Banner links are now being open in a new tab.
Tested locally to verify if the link opens in a new tab.
Fixes https://github.com/celo-org/data-services/issues/508

Open banner link in a new tab

---

apps/block_scout_web/assets/js/lib/analytics.js
apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po

Updates Alfajores and Baklava URLs and fixes some URLs that are semi-hardcoded and work incorrectly with multiple environments on the same domain name.
Hides the "Other Networks" section if there are no other networks configured.
Locally and on staging.
- Relates to https://github.com/celo-org/data-services/issues/440

Fixed URLs to work with multiple envs on the same hostname

---

apps/block_scout_web/assets/css/components/_epoch_tile.scss
apps/block_scout_web/assets/js/lib/async_listing_load.js
apps/block_scout_web/assets/js/lib/epoch_tile.js
apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
apps/block_scout_web/lib/block_scout_web/templates/block_epoch_transaction/index.html.eex
apps/block_scout_web/lib/block_scout_web/templates/epoch_transaction/_election_aggregated_tile.html.eex
apps/block_scout_web/lib/block_scout_web/templates/epoch_transaction/_election_aggregated_tile_transaction_item.html.eex
apps/block_scout_web/lib/block_scout_web/templates/epoch_transaction/_election_tile.html.eex
apps/block_scout_web/lib/block_scout_web/templates/epoch_transaction/_epoch_tile.html.eex
apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
apps/block_scout_web/lib/block_scout_web/views/epoch_transaction_view.ex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
apps/explorer/lib/explorer/chain/celo/celo_election_rewards.ex

Fixes https://github.com/celo-org/data-services/issues/512

Feedback fixes

---

apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
apps/block_scout_web/lib/block_scout_web/templates/address_epoch_transaction/index.html.eex
apps/block_scout_web/lib/block_scout_web/templates/block/_tabs.html.eex
apps/block_scout_web/lib/block_scout_web/templates/epoch_transaction/_election_aggregated_tile.html.eex
apps/block_scout_web/lib/block_scout_web/templates/epoch_transaction/_election_tile.html.eex
apps/block_scout_web/lib/block_scout_web/templates/epoch_transaction/_epoch_tile.html.eex
apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
apps/block_scout_web/lib/block_scout_web/views/block_view.ex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po

Addresses mobile UI issues discovered while testing.
Fixes https://github.com/celo-org/data-services/issues/527

Epoch Rewards: Mobile UI fixes

---

CHANGELOG.md
apps/explorer/lib/explorer/chain.ex
apps/explorer/lib/explorer/token/instance_metadata_retriever.ex
apps/explorer/lib/explorer/token/instance_owner_reader.ex
apps/explorer/test/explorer/chain_test.exs
apps/indexer/lib/indexer/fetcher/token_instance.ex
apps/indexer/test/indexer/fetcher/token_instance_test.exs

This PR brings all the upstream fixes to token instance fetcher since ERC-1155 support merge.

Upstream merges for token instance fetching fixes

---

apps/explorer/priv/repo/migrations/20220902103213_create_index_token_transfers_token_ids.exs
apps/explorer/priv/repo/migrations/20220902103527_create_indexes_token_instances_token_contract_address_hash_token_id.exs

This PR brings missed migrations for the token instances query.

Added token_transfers and token_instances migrations

---

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/epoch_controller.ex
apps/block_scout_web/lib/block_scout_web/views/api/rpc/epoch_view.ex
apps/block_scout_web/test/block_scout_web/controllers/api/rpc/epoch_controller_test.exs
apps/explorer/lib/explorer/chain/celo/celo_election_rewards.ex
apps/explorer/lib/explorer/generic_paging_options.ex

This PR introduces validator endpoint for Epoch rewards API.
- Fixes https://github.com/celo-org/data-services/issues/537

Epoch API: Validator rewards endpoint

---

.github/workflows/config.yml
apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/epoch_controller.ex
apps/block_scout_web/lib/block_scout_web/views/api/rpc/epoch_view.ex
apps/block_scout_web/test/block_scout_web/controllers/api/rpc/epoch_controller_test.exs

This PR adds group rewards Epoch API endpoint.
- Fixes https://github.com/celo-org/data-services/issues/538

Epoch API: Group rewards endpoint

---

apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
apps/block_scout_web/lib/block_scout_web/controllers/csv_export_controller.ex
apps/block_scout_web/lib/block_scout_web/templates/address_epoch_transaction/index.html.eex
apps/block_scout_web/lib/block_scout_web/views/address_epoch_transaction_view.ex
apps/block_scout_web/lib/block_scout_web/views/csv_export.ex
apps/block_scout_web/lib/block_scout_web/views/epoch_transaction_view.ex
apps/block_scout_web/lib/block_scout_web/web_router.ex
apps/explorer/lib/explorer/celo/epoch_util.ex
apps/explorer/lib/explorer/export/csv/csv_export.ex
apps/explorer/lib/explorer/export/csv/exporters/epoch_transaction_exporter.ex
apps/explorer/test/explorer/chain/csv_export/epoch_transactions_csv_exporter_test.exs
apps/explorer/test/support/factory.ex

This PR adds CSV export functionality to Blockscout.
- Fixes https://github.com/celo-org/data-services/issues/523

Epoch CSV Download

---

apps/explorer/lib/explorer/chain/celo/celo_election_rewards.ex
apps/explorer/priv/repo/migrations/20221129130853_remove_zero_amount_rewards.exs
apps/indexer/lib/indexer/fetcher/celo_epoch_data.ex
apps/indexer/test/indexer/fetcher/celo/celo_epoch_data_test.exs

This PR removes zero-amount rewards from the database and makes sure that we don't save them anymore.
- Fixes https://github.com/celo-org/data-services/issues/576

Remove zero amount rewards

---

apps/block_scout_web/lib/block_scout_web/controllers/address_celo_controller.ex
apps/block_scout_web/lib/block_scout_web/controllers/address_epoch_transaction_controller.ex
apps/block_scout_web/lib/block_scout_web/controllers/address_signed_controller.ex
apps/block_scout_web/lib/block_scout_web/templates/address_celo/index.html.eex
apps/block_scout_web/lib/block_scout_web/templates/address_epoch_transaction/index.html.eex
apps/block_scout_web/lib/block_scout_web/templates/address_signed/index.html.eex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po

Fixes missing @tags error while accessing celo-specific address pages:
- Celo Info
- Signed 
- Epoch Transactions
- Fixes https://github.com/celo-org/data-services/issues/599

Error while accessing celo-specific address pages

---

CHANGELOG.md
apps/block_scout_web/config/config.exs
apps/block_scout_web/lib/block_scout_web/controller.ex
apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
apps/explorer/lib/explorer/celo/account_reader.ex

Cherry-picks [this](https://github.com/blockscout/blockscout/commit/195236c0ce9a9a80fb1d39e4235bac028be10f84) and [this](https://github.com/blockscout/blockscout/commit/e6f29fe581960ba34be18bb51f058aab5a18aa47) fixes.
- Fixes https://github.com/celo-org/data-services/issues/605

Fix double slash in the path

---

apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po

Changes wording for next/prev epoch block navigation.
- Fixes https://github.com/celo-org/data-services/issues/600

Change prev/next epoch block navigation wording

---

apps/block_scout_web/lib/block_scout_web/csp_header.ex

Fixes content-security-policy for stats.
Tested on staging.

Fix content-security-policy for stats

---

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/rpc_translator.ex

Fixes bug where all API endpoints started returning "unknown action" error.
Renamed `BlockScoutWeb.API.RPC.RPCTranslator.action_accessed?/2` to `BlockScoutWeb.API.RPC.RPCTranslator.action_permitted?/2` to have more meaningful name and adapted error responses to have more visibility. Such case would from now on be logged as well.
- Fixes https://github.com/celo-org/data-services/issues/635

API returning "unkown action" error

---

apps/explorer/test/explorer/chain/token/instance_test.exs

Fix compilation error

---

apps/explorer/lib/explorer/chain.ex
apps/indexer/lib/indexer/fetcher/token_instance.ex

This PR reverts fixes for missing NFT query due to performance reasons.

Revert nft query fix

---

.github/workflows/helm_deploy_call.yml

Fix helmfile workflow master reference

Fix helmfile workflow master reference

---

apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
helm/values/values-rc1staging-blockscout.yaml

Fixes no function clause error found on mainnet.
None.
- Fixes https://github.com/celo-org/data-services/issues/685

Fix no function clause error found on mainnet

---

.github/workflows/helm_deploy_dispatch.yml

_A few sentences describing the overall effects and goals of the pull request's commits._
_What is the current behavior, and what is the updated/expected behavior with this PR?_
_Describe any minor or "drive-by" changes here._
_An explanation of how the changes were tested or an explanation as to why they don't need to be._
_Add any artifacts (links, screenshots) you can include to increase the reviewers' confidence in the change._
- Relates to #[issue number here]
- Fixes #[issue number here]

Allow deploying rc1staging from non-master branches

---

apps/block_scout_web/assets/js/lib/smart_contract/interact.js

Add sanctioned address

---

CHANGELOG.md
apps/indexer/lib/indexer/fetcher/empty_blocks_sanitizer.ex

Fixing deadlocks in the empty blocks sanitizer.
Cherry picks https://github.com/blockscout/blockscout/commit/042c2cb8751c3207727f35e479101a1eb0ff9b87

Fix deadlocks in empty block sanitizer

---

apps/block_scout_web/assets/js/lib/analytics.js

Temporarily disables tracking.
None.

Temporarily disable analytics

---

apps/block_scout_web/assets/package-lock.json
apps/block_scout_web/assets/package.json
apps/explorer/package-lock.json

Combined dependabot npm upgrades to prevent ci cache from being exploded + self hosted github runners getting exhausted

Combined dependabot upgrades

---

apps/block_scout_web/assets/js/lib/smart_contract/interact.js

Adds an address to the sanctions list
- closes https://github.com/celo-org/data-services/issues/731

Update sanctioned addresses.

---

apps/explorer/mix.exs
mix.lock

Changes a dependency away from clabs-co to celo-org github.
* running on rc1staging
* closes https://github.com/celo-org/data-services/issues/732

Change fly_postgres_elixir dep to celo-org github org.

---

.github/dependabot.yml

Group patch and minor version updates by predefined groups to reduce the amount of version update PRs to review.
New-ish feature: https://github.blog/changelog/2023-08-24-grouped-version-updates-for-dependabot-are-generally-available/
Configuration: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
Automated tests only.
- Relates to https://github.com/celo-org/celo-labs/discussions/1036

Update dependabot.yml with groups

---

.github/workflows/blockscout.yml

upgrade to container ci/cd version 2.0

update to workflow version 2.0

---

.github/workflows/blockscout.yml
apps/block_scout_web/config/navigation.exs

Remove links from nav as requested by security / it.
_An explanation of how the changes were tested or an explanation as to why they don't need to be._
_Add any artifacts (links, screenshots) you can include to increase the reviewers' confidence in the change._

Remove dead links from nav.

---

.github/workflows/blockscout.yml
apps/block_scout_web/config/navigation.exs
apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po

This PR adds a new section `Derivates Platform` to the `More` topbar menu.
The request was done by Celo Foundation and ImmortalX platform.

Added Derivates Platforms to links section
