celo-org/blockscout

apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex

Blockscout-web was sending a bunch of 404s. Turns out favicons weren't being found, probably due to a bug with Plug.Static usage. This PR just sets the URLs of the favicons and apple-touch-icon to static paths.

Hack favicons

---

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex

Our blocks now contain extra data related to our generation of randomness which threw blockscout off.

Adjust to Randomness

---

apps/block_scout_web/lib/block_scout_web/etherscan.ex
apps/block_scout_web/lib/block_scout_web/views/api/rpc/logs_view.ex
apps/explorer/lib/explorer/etherscan/logs.ex

Fix query `curl "http://localhost:4000/api?module=logs&action=getLogs&fromBlock=48486&toBlock=latest&address=0x88F24De331525cf6cFD7455Eb96A9E4D49B7F292"`

Bugfix: getLogs query

---

apps/explorer/config/config.exs

Disable exchange rate module AFA it is failing now (because `COIN` not found on source):
```
iex(1)> 2019-11-28T04:25:41.258 [error] Task #PID<0.6422.5> started from Explorer.ExchangeRates terminating
** (MatchError) no match of right hand side value: {:error, :not_found}
(explorer) lib/explorer/exchange_rates/source/coin_gecko.ex:47: Explorer.ExchangeRates.Source.CoinGecko.source_url/0
(explorer) lib/explorer/exchange_rates/source.ex:17: Explorer.ExchangeRates.Source.fetch_exchange_rates_request/1
(elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
(elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
(stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<0.73601901/0 in Explorer.ExchangeRates.fetch_rates/0>
Args: []
```

Disable exchange rates

---

apps/block_scout_web/lib/block_scout_web/controllers/address_celo_controller.ex

There was an error when trying to show Celo info page for addresses that had no associated Celo account.

Fixing internal server error, show 404 instead

---

apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/_token_transfer.html.eex
apps/explorer/lib/explorer/chain/log.ex
apps/explorer/lib/explorer/chain/token_transfer.ex
apps/explorer/priv/repo/migrations/20180212222309_create_logs.exs
apps/explorer/priv/repo/migrations/20180606135150_create_token_transfers.exs
apps/explorer/priv/repo/migrations/20191011140922_create_celo_account.exs
apps/indexer/lib/indexer/block/fetcher.ex

As a temporary fix, I had added a transaction with hash "0x000..." that was associated to logs with no actual associated transaction. This transaction made tests harder, and also was weird in the web interface. Now shows `System transfer` for token transfers with no associated transaction.
Requires database hard reset.

Removed transaction with "0x000.." hash from DB

---

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex
apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs

There is an error in Blockscout when some verified contract methods return an array of addresses:
https://github.com/poanetwork/blockscout/issues/2907
This change mitigates that error returning an empty array when that happens.
It's necessary to monitor the underlying error in blockscout and apply the patch when it's ready in upstream.

Mitigation error when a contract output is an array of addresses

---

apps/block_scout_web/lib/block_scout_web/controllers/address_signed_controller.ex
apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
apps/block_scout_web/lib/block_scout_web/templates/address_signed/index.html.eex
apps/block_scout_web/lib/block_scout_web/views/address_view.ex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
apps/explorer/lib/explorer/chain.ex

This is probably more helpful, perhaps it would be better to switch between showing all elected bblocks vs. just downtime.

Changed signed tab to downtime

---

apps/explorer/lib/explorer/chain/import/runner/celo_accounts.ex
apps/explorer/test/explorer/chain_test.exs
apps/indexer/lib/indexer/fetcher/celo_validator.ex

Account dedup might have caused the missing attestation stats.
Going to test if it works on my server.
Fixes https://github.com/celo-org/celo-monorepo/issues/2473
(hopefully)

Account dedup fix

---

apps/indexer/lib/indexer/block/fetcher.ex

`Enum.dedup` only removes consecutive duplicates, so had to change it to `Enum.uniq`

Fixing attestation dedup problem

---

apps/block_scout_web/lib/block_scout_web/resolvers/coin_balances.ex
apps/block_scout_web/lib/block_scout_web/schema.ex
apps/block_scout_web/lib/block_scout_web/schema/types.ex
apps/explorer/lib/explorer/graphql.ex

Adds a GraphQL query for coin balance history.
Example query:
```
{
coinBalances(address:"0x73b49DA41223585a650712363BA7878Ed60a964d", first: 100) {
edges {
node {
blockTimestamp
blockNumber
value
}
}
}
}
```

Querying balance history

---

apps/explorer/lib/explorer/chain/import/runner/tokens.ex
apps/explorer/lib/explorer/chain/token.ex
apps/indexer/lib/indexer/block/fetcher.ex
apps/indexer/lib/indexer/fetcher/internal_transaction.ex

Update gold tokens balances when internal transactions have made changes.
Keep updating info about tokens such as `totalSupply`.

Fixing some problems with gold token

---

apps/explorer/lib/explorer/chain.ex
apps/explorer/lib/explorer/graphql.ex

The virtual fields were not fetched for all GraphQL queries involving validators and validator groups, this should fix that.

Adding virtual fields to GraphQL queries

---

apps/indexer/lib/indexer/memory/monitor.ex

This feature seems to be broken, disabling it to make sure that it's never triggered.

Disable GC

---

apps/explorer/lib/explorer/chain.ex

Sample:
```
{
address(hash:"0x6a1b8c919ec3cfb37070b5b9a1b3872c05b1681c") {
hash
celoAccount {
address
name
}
}
}
```

Get correct accounts for signers when using GraphQL

---

apps/explorer/lib/explorer/chain/celo_account.ex

Perhaps needed sometimes to keep the score in sync.

Added event to track validator scores

---

apps/block_scout_web/lib/block_scout_web/controllers/address_contract_controller.ex
apps/block_scout_web/lib/block_scout_web/resolvers/address.ex
apps/block_scout_web/lib/block_scout_web/resolvers/celo_account.ex
apps/block_scout_web/lib/block_scout_web/resolvers/celo_validator_group.ex
apps/block_scout_web/lib/block_scout_web/schema.ex
apps/block_scout_web/lib/block_scout_web/schema/types.ex
apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
apps/explorer/lib/explorer/chain.ex
apps/explorer/lib/explorer/chain/address.ex
apps/explorer/lib/explorer/chain/celo_account.ex
apps/explorer/lib/explorer/graphql.ex
apps/explorer/lib/explorer/smart_contract/reader.ex

Added a way to get info about signers, for example
```
{
celoElectedValidators(blockNumber: 500000) {
hash
online
}
}
```
Added `voters` connection to `celoValidatorGroup` and `voted` connection to `celoAccount`.
Changing how proxy contracts are shown
* Show the code for proxy, not implementation
* In read contract, read from the proxy

Added more data accessible from GraphQL

---

apps/block_scout_web/lib/block_scout_web/schema/types.ex
apps/explorer/lib/explorer/graphql.ex

`voted` query returned the account info for the voter and `voters` returned account info for groups.

Fixing vote query mix up

---

apps/indexer/lib/indexer/transform/celo_accounts.ex

Sometimes the validator membership doesn't update, perhaps this fixes it.

Trying to fix validator membership handling

---

apps/indexer/lib/indexer/buffered_task.ex
apps/indexer/lib/indexer/supervisor.ex

For some reason, the process handling internal transactions couldn't recover when the initial state had errors.

Buffered task issue

---

apps/explorer/config/config.exs
bin/install_chrome_headless.sh

The health endpoint wasn't working correctly when the `HEALTHY_BLOCKS_PERIOD` was passed.

Changed parsing of the HEALTHY_BLOCKS_PERIOD env var

---

CHANGELOG.md
apps/explorer/lib/explorer/chain/address/coin_balance.ex

Current query in fetch_coin_balance function causes performance issues.
In order to address the performance of the query replace
```
SELECT a0."block_number", a0."value", a0."value_fetched_at", a0."inserted_at", a0."updated_at", a0."address_hash", value - coalesce(lag(value, 1) over (order by block_number), 0), b1."timestamp" FROM "address_coin_balances" AS a0 INNER JOIN "blocks" AS b1 ON a0."block_number" = b1."number" WHERE (a0."address_hash" = '\...') AND (a0."block_number" <= ...) ORDER BY a0."block_number" DESC LIMIT 1;
```
with
```
SELECT c."block_number", c."value", c."value_fetched_at", c."inserted_at", c."updated_at", c."address_hash", value - coalesce(lag(value, 1) over (order by block_number), 0) from (select a0."block_number", a0."value", a0."value_fetched_at", …
```

Fix fetch_coin_balance query: coin balance delta

---

apps/explorer/lib/explorer/graphql.ex

Valora (and blockchain-api particularly) still relies on `cGLD`. Support for `CELO` should be added there first then updated in here.

Reverted the CELO symbol for graphql

---

cloudbuild.yaml
docker/Dockerfile

Adds a new docker image (tagged as `api-$hash`) built with `DISABLE_WRITE_API=true` as defined in https://docs.blockscout.com/for-developers/information-and-settings/env-variables.

Add Cloudbuild step for building API docker image

---

apps/indexer/config/config.exs
apps/indexer/lib/indexer/application.ex
apps/indexer/lib/indexer/health.ex
apps/indexer/lib/indexer/health/plug.ex

Adds health check endpoints `/health/liveness` and `/health/readiness` that can be used in k8s probes.

Indexer health check endpoint

---

apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po

Removes unused links to networks and adds the mainnet link. Resolves https://github.com/celo-org/blockscout/issues/147 and https://github.com/celo-org/celo-monorepo/issues/5879.

Updated the list of networks

---

apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
apps/explorer/lib/explorer/etherscan.ex

Fixes #167.
Adds 3 additional fields to the txlist `API` response:
* `feeCurrency`. String, not nullable, one of `cUSD`, `CELO`.
* `gatewayFee`. String, not nullable.
* `gatewayFeeRecipient`. String, if there is no gateway fee, returns an empty string.

Added gateway fee recipient information

---

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/token_controller.ex
apps/block_scout_web/lib/block_scout_web/views/api/rpc/token_view.ex
apps/block_scout_web/test/block_scout_web/controllers/api/rpc/token_controller_test.exs
apps/explorer/lib/explorer/etherscan.ex

Currently, there is no way to fetch native CELO transfers in the given block range, while it's possible for cUSD. The Notification service misses native transfers and doesn't notify users because of that.
The endpoint call looks like `curl --silent "https://explorer.celo.org/api?module=token&action=tokentx&fromBlock=3282183&toBlock=3282286&contractaddress=0x471ece3750da237f93b8e339c536989b8978a438"`.
There are 3 required parameters:
- `fromBlock`, integer, starting block.
- `toBlock`, integer or `latest`, end block.
- `contractaddress` - contract address of the token, works for both CELO and cUSD.
Example output:
```
{
"status": "1",
"result": [
{
"transactionIndex": "7",
"transactionHash": "0xe36c8ca582643165094fd9f589002433c708d566786194d3c32b797183463f4d",
"topics": [ …
```

Implemented token transfers with logs endpoint

---

cloudbuild.yaml

Build times out pretty often as we build two images. Increasing it to 3600 seconds.

Fixed timeouts for cloudbuild

---

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/stats_controller.ex
apps/block_scout_web/lib/block_scout_web/etherscan.ex
apps/block_scout_web/lib/block_scout_web/views/api/rpc/stats_view.ex

celo.org needs an API endpoint that would return the total number of transactions on the chain.
This PR adds a new action `totaltransactions` to the `stats` API module, https://alfajores-blockscout.celo-testnet.org/api?module=stats&action=totaltransactions.

Added total transactions stats endpoint

---

apps/block_scout_web/test/block_scout_web/controllers/api/rpc/token_controller_test.exs
apps/explorer/lib/explorer/etherscan.ex

The endpoint returns incorrect results for multiple transfers in one transactions.
This PR fixes the SQL query, joining on both transaction hash AND log index.

Fixed the token transfers endpoint

---

apps/block_scout_web/assets/css/components/_cookie_banner.scss
apps/block_scout_web/assets/css/components/_network-selector.scss

Items in the dashboard banner overlapped the cookie banner
Adjusted z-indexes
Navbar: 100
Network Selector: 110
Cookie Banner: 120

fix z-indexes

---

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/contract.ex
apps/explorer/lib/explorer/token/balance_reader.ex

This fixes #222, making blockscout work with the current master of celo-blockchain.
Note: we tested this on testnets with celo-blockchain master and with an older version from before the relevant changes.  However, as I have no developed on blockscout before and don't have the dev environment set up, I did not do the usual set of checks that you would do. 
* `eth_call` and `Explorer.Token.BalanceReader` (which uses `eth_call`) have been updated to not specify the `gasPrice`.  With v1.2.x and earlier of celo-blockchain, the node will set the gas price itself, while with newer versions (current master), it will default gas to gas price of 0, which is allowed for `eth_call` and for gas estimation.
Some context regarding this change: older versions of geth, and celo-blockchain up to v1.2.x …

Leave out gasPrice when using `eth_call`

---

apps/explorer/lib/explorer/graphql.ex

The query that resolves the account address is very slow as it uses the nested loop strategy. This fixes a typo that caused that suboptimal fix.
Query plan before: https://explain.depesz.com/s/y7vRJ
Query plan after: https://explain.depesz.com/s/A0Ms
Speed up of the transfers query, the fix will reduce the db CPU utilization.

Speed up the query

---

apps/ethereum_jsonrpc/priv/js/ethereum_jsonrpc/geth/debug_traceTransaction/tracer.js

We faced method handler crashed error in Kotti
```
[%{code: -32000, data: %{block_number: 1743966, transaction_hash: "0x0e439d91608cfcd2ff89ca9345bb8a93a4f1522fe82a0666e21f02afa7011848", transaction_index: 0}, message: "method handler crashed"}]
```
I found similar issues but there is no solution yet
https://github.com/poanetwork/blockscout/issues/3234
https://github.com/poanetwork/blockscout/issues/2445
But I found that in our case in Kotti this transactions is contact creation tx. But tx doesn't has input (so no contract code). 
```
{
"jsonrpc": "2.0",
"method": "eth_getTransactionByHash",
"params": ["0x0e439d91608cfcd2ff89ca9345bb8a93a4f1522fe82a0666e21f02afa7011848"],
"id": 83
}
{
"jsonrpc": "2.0",
"id": 83,
"result": {
"blockHash": …
```

Fix trace internal transactions for create contract without code

---

apps/indexer/lib/indexer/transform/token_transfers.ex

When an internal transaction creates a contract, the parser fails with an error:
```
{"error":{"initial_call":null,"reason":"** (KeyError) key :call_type not found in: %{block_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<69, 115, 67, 163, 195, 102, 136, 70, 7, 240, 27, 54, 144, 200, 138, 81, 142, 147, 241, 173, 54, 73, 86, 201, 176, 213, 100, 239, 164, 172, 92, 152>>}, block_number: 4561476, created_contract_address_hash: \"0x1733ed9570c574e2c4b54fc06415d7c5def5a71c\", created_contract_code: \"0x608060405234801561001057600080fd5b50600436106100935760003560e01c8063674f220f11610066578063674f220f146101225780638da5cb5b1461016" <> ..., trace_address: [0], transaction_hash: \"0x060590514b5ec2fc5933be947b35757733447fc2e45394a253cef8eca6d7ca15\", transaction_index: 1, type: \"create\", …
```

Fixed an issue with internal transaction of CREATE type

---

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex

We keep watching some timeouts on the `debug_traceTransaction` calls. 
Increased the timeout to 100 seconds.

Increase debug trace transaction calls timeout to 100secs

---

apps/explorer/lib/explorer/chain/address.ex

Related with #287
Taking into  account the current error, we are going to avoid to encode the implementation contract in the address.

Avoid to encode the implementation address

---

apps/explorer/lib/explorer/chain.ex

The way fetching coinsupply was written, it would throw an error if there was no value set for `sum_coin_total_supply_minus_burnt` in the `last_fetched_counters` table. With this change, we return 0 instead of throwing an error.
Fixes #284

Fix coinsupply fetching

---

apps/explorer/lib/explorer/chain.ex

In the case of leading and trailing non-alphanumeric characters, these would be converted to `&`s and this messes with the text search query. Added code to remove them.
Closes #294

Remove leading and trailing &s

---

.github/CODEOWNERS

For some reason @eruizgar91 is being set as the required reviewer for all new pull requests, probably because that is the last line in the codeowners file. 
This PR changes it so there is a single line, hopefully this resolves it.

Fix codeowners formatting.

---

apps/explorer/lib/explorer/graphql.ex

Positional bindings in this query are incorrect due to a new fragment being added. This PR changes it to use named bindings for this statement and avoid positional errors.
closes #296

Use named binding for transaction in celo_tx_transfers_query.

---

apps/explorer/lib/explorer/chain.ex
apps/explorer/lib/explorer/chain/events/listener.ex
apps/explorer/lib/explorer/repo.ex
apps/explorer/lib/explorer/repo/config_helper.ex
apps/explorer/test/explorer/chain_test.exs
apps/explorer/test/explorer/repo/config_helper_test.exs
apps/explorer/test/explorer/repo_test.exs

* Extracts parameters from DATABASE_URL value and stores them in `Repo` config
* Only sets values if they don't already exist in options provided to `Repo`
* Removes similar logic from Chain context
* Closes #299

Extract database parameters from DATABASE_URL.

---

.github/workflows/config.yml
apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/rolling_window.ex
mix.exs

Optimises the workflow by aggressively caching dependencies. 
Notably :
* Cache elixir dependencies
* Cache npm node_modules
* Cache dialyzer persistent lookup table (plt)
These caches are keyed on their respective lock files, for npm this is the `package-lock.json` files in `explorer` and `block_scout_web` apps, for dialyzer and elixir dependencies this is `mix.lock`. These caches will be rebuilt upon changes to npm modules or elixir dependencies, which will result in an initially longer build time but will be persisted across test runs.
Initial results seem to show a reduction in test run time from ~23 minutes to around 14 minutes. Currently the test runs are bounded by the `explorer` test suite, specifically smart contract verification functionality. Further reductions would likely …

Optimise github actions

---

apps/explorer/lib/explorer/graphql.ex

The coinBalances query was causing an internal server error. That's because the custom scalar :wei is expecting a map with a "value" key in its serialize function. The way the code was written, the delta field of coinBalances was just a Decimal and that led to the error.

Wrap coin balances delta in map with key "value"

---

apps/block_scout_web/lib/block_scout_web/resolvers/celo_parameters.ex

maxElectableValidators, minElectableValidators and numRegisteredValidators were returned as decimals when they should be integers.

Convert params to integer before returning them

---

.github/workflows/config.yml
apps/explorer/test/explorer/smart_contract/publisher_test.exs
apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs
apps/explorer/test/explorer/smart_contract/verifier_test.exs

* Exclude smart contract verifier tests by default
* These tests each spin up an external nodejs process to run an external verification program
* They do this sequentially
* We don't use this feature in the Celo explorer (we rely entirely on Sourcify integration)
* This brings the explorer test suite duration down from 12 minutes to ~3 minutes
* Add workflow action to collect junit files and display in a useful fashion
* It turns out we already create junit test output but don't use it
* Now we do

Quality of life test changes

---

.github/workflows/config.yml

Tests were failing due to missing environment variables, this PR sets environment variables on test run steps of the CI build process, rather than on the last step of the job.

Set env on test runs.

---

apps/block_scout_web/assets/js/app.js
apps/block_scout_web/assets/js/lib/analytics.js
apps/block_scout_web/assets/js/view_specific/raw-trace/code_highlighting.js
apps/block_scout_web/assets/js/view_specific/raw_trace/code_highlighting.js

Including the staking page to the app.js bloats all the js bundles with unnecessary web3 dependency.
Before:
After:
Optimizes the size of the code highlighting script by removing unnecessary dependencies and including only relevant languages to the build. And fixes the 404 issue for the script on the raw traces tab.
Tested in the browser.
Yes.

Reduced the size of js bundles

---

apps/indexer/lib/indexer/fetcher/token.ex

Sets a poll config on the token fetcher to periodically stream uncataloged tokens from the database for reindexing. This is similar to how the internal transaction fetcher retrieves a list of unprocessed blocks to fetch transactions for.
* Deployed to staging and changed some token values
* Set `name` and `symbol` to placeholder values and `cataloged` to false
* After 60 seconds they were reindexed with the previous (correct) values
- Relates to celo-org/data-services#46

Set poll options on token fetcher.

---

apps/indexer/lib/indexer/fetcher/internal_transaction.ex

Changes internal transaction settings in a way that makes the indexer to process pending block operations faster. Larger batch sizes generate less load on the DB but take longer to process all the transactions in the batch that increases the time in the queue.
None.
Tested in production.
Yes.

Changed default internal transactions settings

---

apps/explorer/lib/explorer/celo/core_contracts/core_contract_cache.ex

`StableTokenREAL` isn't yet in the core contracts list and will cause a fail if it is treated as such. To workaround this, this PR adds it manually so that it can be queried.
Also adds the ability to update the cache incrementally, and will try to fetch empty addresses whenever they are requested.
relates to #431

Add StableTokenREAL to cache

---

apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
apps/block_scout_web/test/block_scout_web/controllers/api/rpc/transaction_controller_test.exs
apps/explorer/lib/explorer/chain.ex
apps/explorer/test/explorer/chain_test.exs

Blockscout doesn't display the revert reason although this functionality exists. The parsing function relies on the `data` field of the RPC response, while in geth `data` contains binary data:
```
curl -s --data '{"jsonrpc":"2.0","method":"eth_call","params":[{"data":"0x1c5a9d9c0000000000000000000000004da92da1afbf103f2b52dd29326e34c98ca1e78c","from":"0x4a4f08188b99baa1b98f8027da69e3a679c0578c","to":"0x8d6677192144292870907e3fa8a5527fe55a7ff6","gas":"0x33450","gasPrice":"0x1dcd6500","value":"0x0"},"0x978DA1"],"id":0}' http://127.0.0.1:8546  -H 'Content-type: application/json'
{
"jsonrpc": "2.0",
"id": 0,
"error": {
"code": 3,
"message": "execution reverted: Pending vote …
```

Display revert reason

---

apps/indexer/lib/indexer/buffered_task.ex
apps/indexer/lib/indexer/fetcher/internal_transaction.ex
apps/indexer/test/indexer/buffered_task_test.exs

BufferedTask is the behavior used by fetchers (and the internal transactions fetcher, in particular). It's an abstraction built around `BoundQueue` that can be used for creating a long-running process that periodically fetches new units of work from the source, enqueues them and then processes in batches with configured batch size and concurrency.
When it starts, it calls the `init` method that provides the initial list of units of work that gets immediately enqueued into the `bound_queue`. If the `poll` parameter is `true`, the `init` method will be called with the `poll_interval` periodicity. Items from this queue get dequeued with the `flush_interval` periodicity, …

Duplicates of pending blocks in the queue

---

apps/indexer/lib/indexer/fetcher/celo_epoch_rewards.ex

`Indexer.Fetcher.CeloEpochRewards` knows which blocks to index by looking into the `celo_pending_epoch_operations` table. Without this PR, the fetcher only looks once at the beginning. By setting `poll` to true, it looks every 1 hour.
Tested by 
- deploying to staging
- removing the last entry to `celo_epoch_rewards`
- inserting the deleted entry's `block_hash` to `celo_pending_epoch_operations`
- seeing that it was properly indexed

Enable polling in epoch fetcher

---

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/token_controller.ex
apps/block_scout_web/lib/block_scout_web/etherscan.ex
apps/block_scout_web/test/block_scout_web/controllers/api/rpc/token_controller_test.exs
apps/explorer/lib/explorer/etherscan.ex

The following query is super slow:
https://explorer.celo.org/api?module=token&action=tokentx&contractaddress=0x765de816845861e75a25fca122bb6898b8b1282a&fromBlock=7013880&toBlock=latest
The underlying SQL query is:
```
SELECT
t2."token_contract_address_hash",
t2."transaction_hash",
t2."from_address_hash",
t2."to_address_hash",
t2."amount",
b0."timestamp",
t1."index",
l3."index",
l3."data",
l3."first_topic",
l3."second_topic",
l3."third_topic",
l3."fourth_topic",
t1."block_number",
t1."gas_price",
t1."gas_currency_hash",
t1."gas_fee_recipient_hash",
t1."gas_used",
t1."gateway_fee"
FROM "blocks" AS b0
LEFT OUTER JOIN "transactions" AS t1
ON t1."block_number" = b0."number"
LEFT OUTER JOIN "token_transfers" AS t2
ON t2."transaction_hash" = t1."hash"
LEFT OUTER JOIN "logs" AS l3
ON( …
```

Speed up the tokentx query

---

apps/explorer/lib/explorer/chain.ex
apps/explorer/lib/explorer/chain/cache/transaction_count.ex
apps/explorer/test/explorer/chain/cache/transaction_count_test.exs
apps/explorer/test/explorer/chain_test.exs

The total TX count is stored in ETS cache only and the API method that is supposed to return it always falls back to fetching an estimated value based on the number of tuples in the table. This method is fast but, unfortunately, leads to very intermittent results and usually never returns correct values.
There is a job that updates cache value every 2 hours by default with accurate values using the `SELECT *` query.
This PR persists the value of the cache in the counters table so it can be reused by API.
Fixes the method that returns last fetched counters.
Added a test to make sure that there is no regression in `get_last_fetched_counter`.
Added a test to check that the cached value is saved in the counters table.
- Fixes https://github.com/celo-org/data-services/issues/164
Yes.

Persisted cached TX count

---

apps/explorer/lib/explorer/chain/import/stage/address_referencing.ex
apps/explorer/lib/explorer/chain/import/stage/block_referencing.ex

Errors due to importing contract events are preventing two blocks from being imported on the RC1-3 environment. This issue hasn't yet been seen on the live explorer. Ultimately events are in certain circumstances being imported before transactions which causes a foreign key constraint to fail. 
This PR moves the import stage to have the same priority as the log import, just after transactions. 
* Passed unit tests
* To test on staging before live deploy
- relates to #564

Move Runner.CeloContractEvent into BlockReferencing import stage.

---

apps/explorer/lib/explorer/chain.ex
apps/explorer/test/explorer/chain_test.exs

closes celo-org/data-services#176 for real this time
Last PR fixed the cause of the crash but did not restore functionality to the empty search filter case. Now a tupled string is returned which allow the app to treat the search as if no filter was applied (instead of an invalid filter)
* Modified and ran unit test
* Actually ran the app against the staging DB this time and saw the token page load correctly

Return tupled string from prepare_search_term in case of nil value.

---

README.md
apps/explorer/lib/explorer/celo/events/contract_events/base/contract_event_base.ex
apps/explorer/lib/explorer/celo/events/contract_events/common.ex
apps/explorer/lib/explorer/celo/events/contract_events/election/epoch_rewards_distributed_to_voters_event.ex
apps/explorer/lib/explorer/celo/events/contract_events/event_map.ex
apps/explorer/lib/explorer/celo/validator_group_rewards.ex
apps/explorer/lib/explorer/celo/validator_rewards.ex
apps/explorer/lib/explorer/celo/voter_rewards.ex
apps/explorer/lib/explorer/celo/voter_rewards_for_group.ex
apps/explorer/lib/explorer/chain/celo_contract_event.ex
apps/explorer/lib/explorer/chain/import/runner/celo_contract_event.ex
apps/explorer/lib/mix/tasks/event_map.ex
apps/explorer/priv/repo/migrations/20220315145714_block_number_and_topic_on_events.exs
apps/explorer/test/explorer/celo/events/celo_contract_events_test.exs
apps/explorer/test/explorer/celo/events/epoch_rewards_distributed_to_voters_event_test.exs
apps/explorer/test/explorer/celo/events/event_map_test.exs
apps/explorer/test/explorer/celo/voter_rewards_for_group_test.exs
apps/explorer/test/support/setup_validator_and_group_rewards_test.ex
apps/explorer/test/support/setup_voter_rewards_test.ex
apps/indexer/lib/indexer/fetcher/celo_validator_group_votes.ex
apps/indexer/test/indexer/fetcher/celo_validator_group_votes_test.exs

relates to celo-org/data-services#189
* Modifies `celo_contract_events` schema
* Adds block_number and topic 
* block number is used in pretty much every query, and denormalizing here provides a lot of utility to an individual event
* Removes block_hash 
* Modifies the app to use block_number on the event instead of joining against the blocks table
* Modified and ran all unit tests

Add block_number and topic to celo_contract_events

---

apps/explorer/lib/explorer/celo/events/contract_events/event_map.ex
apps/explorer/lib/mix/tasks/event_map.ex
apps/explorer/lib/mix/tasks/event_map_template.eex
apps/explorer/test/explorer/celo/events/event_map_test.exs

Adds a test to assert that the event map covers the set of events that are defined within the application.
Updates the map to reflect the current state of the application.
* added and ran unit tests

Add test to fail suite if event map doesn't cover all the events in the application

---

apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex
apps/block_scout_web/lib/block_scout_web/views/tokens/helpers.ex
apps/block_scout_web/test/block_scout_web/views/tokens/helpers_test.exs

Currently, when accessing token page that has empty (`nil`) symbol it fails to load. 
Apart from fixing bug itself, added a case of empty (`""`) token name while building token name (for displaying in meta tags). Without it, it would be displayed as ` - <network> - BlockScout`.
https://app.zenhub.com/workspaces/data-services-sprint-60103a7bf450290020c3800c/issues/celo-org/data-services/204

204: Internal server error on a token with no symbol

---

apps/ethereum_jsonrpc/config/config.exs
apps/indexer/lib/indexer/fetcher/internal_transaction.ex

Changes parameters of the internal TX fetcher to reduce load on the pool of archive nodes.
No.
Tested on all envs.
Yes.

Changed the indexer parameters

---

CHANGELOG.md
apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
apps/explorer/test/explorer/chain/import/runner/internal_transactions_test.exs

For [some transactions](https://explorer.celo.org/tx/0x27e51374271f99dc6a871e6b38f97f584aa04b598a5ad246cb24c12867eba4d0/token-transfers) the `gasUsed` value is `0`, although if you fetch the transaction receipt, it's obviously non-zero:
```
curl -s -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x27e51374271f99dc6a871e6b38f97f584aa04b598a5ad246cb24c12867eba4d0"],"id":1}' https://forno.celo.org  -H 'Content-type: application/json' | jq '.'
{
"jsonrpc": "2.0",
"id": 1,
"result": {
"blockHash": "0x49ee01a5c86a21af2d6f9b73b9905e31c0f61663077a3450269e7c0cd1a96902",
"blockNumber": "0x95b708",
"contractAddress": null,
"cumulativeGasUsed": "0x230d2b",
"from": "0x6ec033738b388d0605b287bc3e375063a4039942",
"gasUsed": "0x520c",
"logs": [],
"logsBloom": …
```

Use gas used from TX receipts

---

.github/CODEOWNERS
apps/explorer/lib/explorer/celo/events/contract_events/common.ex
apps/explorer/lib/mix/tasks/event_map_template.eex
apps/explorer/test/explorer/celo/events/validator_ecdsa_public_key_updated_event_test.exs

closes celo-org/data-services#231
Changesets with an event containing a parameter of type `bytes` were being cast to utf8 strings, this doesn't work in the general case as a binary object can contain byte sequences that represent invalid utf8 codepoints. 
Instead this PR changes the behavior to treat these parameters the same as sized binary parameters (e.g. `{:bytes, 32}` as opposed to just `:bytes`). This stores them in the db as arrays of int values.
* modifies the CODEOWNERS file so that the repo is now owned by data-services instead of `core-services`

Handle event properties of type `bytes` with unspecified size the same as with specified size

---

apps/explorer/lib/explorer/celo/events/contract_events/base/contract_event_base.ex
apps/explorer/lib/explorer/celo/events/contract_events/common.ex
apps/explorer/test/explorer/celo/events/celo_contract_events_test.exs
apps/explorer/test/explorer/celo/events/epoch_rewards_distributed_to_voters_event_test.exs
apps/explorer/test/explorer/celo/events/event_map_test.exs
apps/explorer/test/explorer/celo/events/validator_group_vote_activated_event_test.exs
apps/explorer/test/support/setup_validator_and_group_rewards_test.ex
apps/explorer/test/support/setup_voter_rewards_test.ex
apps/explorer/test/support/test_param_collision_event.ex
apps/indexer/lib/indexer/block/fetcher.ex
apps/indexer/test/indexer/fetcher/celo_validator_group_votes_test.exs

After generating some more events it turns out that collisions with existing struct properties are more likely than first expected. Structs are created based on event ABIs, and if these events happen to define a property that already exists within the struct the original definition will be overwritten and database constraints can't be satisfied when trying to insert.
e.g. if an event was to define a property `name` or `contract_address_hash`, these would be overwritten in the original event.
This PR modifies the existing "meta" properties (properties about the event - `transaction_hash`, `block_number` etc) upon concrete event instances to include a common prefix in order to reduce name collisions. These properties are now referred to by `__transaction_hash` and `__block_number`
A similar …

Prevent name collisions of generated event properties against event "meta" properties

---

apps/explorer/lib/explorer/celo/events/contract_events/base/contract_event_base.ex
apps/explorer/lib/explorer/celo/events/contract_events/common.ex
apps/explorer/test/explorer/celo/events/celo_contract_events_test.exs

Events with unindexed parameters of type `address` were being treated as binary objects and then coerced into invalid UTF8 strings which the database would not accept.
> Note: "unindexed" in this context refers to the fact that the parameter is contained within the `data` field of a log object, and not within it's own topic
This PR changes the behavior to treat all addresses the same, and encode them in the same format as other addresses.
* Renamed a method in the base event macro to better explain what it does
* Added and ran unit test
- closes celo-org/data-services#241

Handle unindexed addresses the same as indexed

---

apps/block_scout_web/assets/js/pages/verified_contracts.js
apps/block_scout_web/assets/webpack.config.js
apps/block_scout_web/lib/block_scout_web/templates/verified_contracts/_tile.html.eex
apps/block_scout_web/lib/block_scout_web/templates/verified_contracts/index.html.eex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po

Adding a tooltip on verified contracts page for "Verified" and "Partially verified labels" with links to sourcify. That way it will be clear for our users what those statuses mean.
- Fixes #647

Verified contracts: tooltips

---

apps/explorer/priv/repo/migrations/20220530155133_add_locks_monitoring.exs

Adds a debugging view that would help with analysing database locks.
Usage:
```
SELECT * FROM dbg_lock_monitor;
```
No.
Tested on staging.
- Fixes https://github.com/celo-org/data-services/issues/242.
Yes.

Added DB locks monitor view

---

apps/explorer/lib/explorer/celo/events/contract_events/common.ex
apps/explorer/test/explorer/celo/events/celo_contract_events_test.exs
bin/data_migration.sh

There is an event `SlasherWhitelistAdded` on the LockedGold contract which has a string as an indexed parameter which was being incorrectly handled. 
Indexed parameters of dynamic types (`string`, `bytes` - other types without explicit size) need to be handled differently than unindexed parameters, as the solidity compiler will replace these types with 32 bit hashes of their values https://docs.soliditylang.org/en/develop/abi-spec.html#indexed-event-encoding
This PR changes the behaviour of event decoding to handle this correctly.
* Changed the data migration script to correctly take the namespace from provided arguments
* Added and ran unit tests
- Relates to celo-org/data-services#190

Handle indexed strings within events

---

apps/block_scout_web/lib/block_scout_web/templates/stats/index.html.eex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po

Renames the name of the dashboard tab to `Mento Reserve`.
No.
Locally.

Renamed Celo Reserve to Mento Reserve

---

apps/block_scout_web/lib/block_scout_web/templates/address/_link.html.eex
apps/block_scout_web/lib/block_scout_web/views/access_helpers.ex
apps/block_scout_web/test/block_scout_web/controllers/tokens/holder_controller_test.exs

Previously upon accessing links generated by `link` partial 2 redirects where happening (first one because it wasn't proper mixed-case and second one because it was redirecting to `/transactions` page). The fix is to generate the "final" link in the partial, so no redirects happen at all.
- Fixes https://github.com/celo-org/data-services/issues/162

Avoid unnecessary redirects

---

apps/explorer/lib/explorer/graphql.ex

This PR adds `token_type` to a query that Valora is using (it was supposed to be done in https://github.com/celo-org/blockscout/pull/684, but they're using different query).

Fix GraphQL query

---

apps/block_scout_web/lib/block_scout_web/schema/types.ex
apps/explorer/lib/explorer/graphql.ex
load-testing/schema.gql

This PR exposes `token_id` field to graphQL transfer queries.
Fixes https://github.com/celo-org/data-services/issues/353

Expose Token ID in graphQL query

---

apps/indexer/lib/indexer/prometheus/metrics_cron.ex
apps/indexer/lib/indexer/supervisor.ex

Runs `metrics_cron` operatoins in parallel so that slow db queries don't prevent the exposure of all metrics. Refactors the structure of the module to be discrete functions rather than a single large function.
* Ran locally against staging and saw metrics displayed on the prometheus endpoint

Parallelise metrics cron operations

---

apps/indexer/lib/indexer/transform/token_transfers.ex
apps/indexer/test/indexer/transform/token_transfers_test.exs

Currently every every first token transfer derived from internal transactions would overwrite data from first transaction in the block (when `log_index` equals to 0). Consequent numbers for internal transactions would be then -1, -2 and not generating conflict on `block_hash, log_index`, so the fix is to start from -1 instead of 0.
Fixes https://github.com/celo-org/data-services/issues/390

Fix updated transactions issue

---

apps/explorer/priv/repo/migrations/20220712081709_updated_at_indices.exs

Adds indices to various tables in order to aid replication to bigquery.
* Migrated and rolled back local db without issue
* This migration will likely take a long time due to the size of the `token_transfers` table. It should be possible to run concurrently without impacting the indexing process, but issues have been seen before due to autovacuum processes causing locking problems (in this instance the indexer + web pods will have to be scaled down during the migration)
* Implements https://github.com/celo-org/data-services/issues/357

Add indices to `updated_at` timestamp on various tables

---

apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
apps/explorer/lib/explorer/etherscan.ex

In https://github.com/celo-org/blockscout/pull/533 the txlist API query was optimized. It works properly when pagination parameters are omitted defaulting to the max of 10_000 items in the result. It fails to get past page 3 when the page size is explicitly set.
No.
Added a unit test.
- Fixes https://github.com/celo-org/data-services/issues/381
Yes.

Fixed txlist pagination issue

---

apps/indexer/lib/indexer/fetcher/empty_blocks_sanitizer.ex

As we need to reenable empty blocks sanitizer the query needs to be optimised. This PR is an attempt to achieve better performance.
Fixes https://github.com/celo-org/data-services/issues/408

Reenable empty blocks sanitizer (with optimized query)

---

apps/explorer/lib/explorer/chain.ex
apps/indexer/lib/indexer/prometheus/metrics_cron.ex

The pending TXs metric collection is very slow as it fetches all rows from the db instead of just the total number. Since it's a heavy request and it's executed very often it generates a significant load on the database.
This PR changes it.
Explicit casting to integer of the age of the latest block (seems to be a change between Postgres versions).
Yes.
- Fixes [#[issue number here]](https://github.com/celo-org/data-services/issues/424)
Yes.

Changed pending txs query

---

apps/indexer/lib/indexer/fetcher/internal_transaction.ex

Increases concurrency and batch size settings of the internal TXs fetcher. Higher values work better with the larger pool of archive nodes.
No.
Tested in production.
- Fixes https://github.com/celo-org/data-services/issues/435
Yes.

Updated internal TXs fetcher concurrency settings

---

apps/explorer/priv/repo/migrations/20220829132236_pg_hero_changes.exs

PG hero states the following 
```
Duplicate Indexes
These indexes exist, but aren’t needed. Remove them for faster writes.
Details
--
On address_names address_names_address_hash_index (address_hash) is covered by unique_address_names (address_hash, name)
On blocks blocks_miner_hash_index (miner_hash) is covered by blocks_miner_hash_number_index (miner_hash, number)
On celo_contract_events celo_contract_events_block_number_index (block_number) is covered by celo_contract_events_pkey (block_number, log_index)
On celo_signers celo_signers_address_index (address)is covered by celo_signers_address_signer_index (address, signer)
On clabs_contract_event_trackings clabs_contract_event_trackings_smart_contract_id_index (smart_contract_id) is covered by smart_contract_id_topic (smart_contract_id, …
```

Add migration to remove duplicate indices.

---

apps/block_scout_web/mix.exs
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
apps/explorer/config/config.exs
apps/explorer/config/test.exs
apps/explorer/lib/explorer/application.ex
apps/explorer/lib/explorer/chain/events/db_source.ex
apps/explorer/lib/explorer/chain/events/listener.ex
apps/explorer/lib/explorer/chain/events/pubsub_sender.ex
apps/explorer/lib/explorer/chain/events/pubsub_source.ex
apps/explorer/mix.exs

Refactors the `pg_notify` chain event functionality to operate in a single configurable module, and adds a new implementation to publish over `Phoenix.PubSub` instead.
* Removed the chain event listener from the indexer app
* The indexer was by default listening to chain events that it was itself publishing, but had no subscribers (except for a test)
* Regenerated translations for some reason
* Deployed to rc1staging and saw events being received on web pod 
* No running "LISTEN" queries on rc1staging db
- Relates to https://github.com/celo-org/data-services/issues/443

Send chain events over PubSub

---

apps/block_scout_web/mix.exs
apps/explorer/lib/explorer/chain.ex

Upstream code doesn't handle the situation where the archive node returns no data for a given address. This PR changes the default implementation to fail safe and treat the contract address as not mutated instead of throwing a 500 error
* Ran locally and was able to access the write contract page
* Passed test suite
- Fixes https://github.com/celo-org/data-services/issues/468

Handle situation where no code is fetched from blockchain.

---

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/rpc_translator.ex

Valora require `/api/` request path to get token balances correctly, this hasn't been supported since the last deploy. This PR just adds it to the list of valid paths.

Explicitly add `api` to allowed request paths for valora compatiblity.

---

apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_via_json_controller.ex
apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
apps/block_scout_web/lib/block_scout_web/notifier.ex
apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_via_json/submitted.html.eex
apps/explorer/config/config.exs
apps/explorer/lib/explorer/application.ex
apps/explorer/lib/explorer/celo/pubsub.ex
apps/explorer/lib/explorer/repo.ex
apps/explorer/lib/explorer/smart_contract/solidity/publisher.ex
apps/indexer/config/config.exs
apps/indexer/lib/indexer/celo/write_operation_handler.ex
apps/indexer/lib/indexer/supervisor.ex

Uses cluster communication to submit a smart contract for verification from web / api pod against an indexer pod. This requires the indexer to listen for contract submission events and to perform the actual verification. 
Due to this being an async operation a message is now displayed after the submission to inform the user that this is happening. This assumes that replication lag is low enough that the contract will be available in the replica db by the time the "View Contract" button has been clicked - given current stats this seems to be a reasonable assumption, but this approach may have to change in future.
* Set `application_name` on replica1 repo instance so that it's connections appear in `pg_stat_activity` with the correct name
* deployed to rc1staging and saw verified contracts …

Verify contracts asynchronously from web / api pod on indexer pod

---

apps/explorer/lib/explorer/chain/import/runner/celo_epoch_rewards.ex
apps/indexer/test/indexer/fetcher/celo/celo_epoch_data_test.exs

After merging [a fix for how we fetch reserve bolster value](https://github.com/celo-org/blockscout/pull/762) all values were reset to 0. But after deploying the fix those values were not successfully saved. This PR fixes it.
Unit tests passed.
Fixes https://github.com/celo-org/data-services/issues/509

Fix to update reserve bolster value on runner conflict

---

apps/explorer/lib/explorer/celo/pubsub.ex
apps/explorer/lib/explorer/chain/import.ex
apps/indexer/config/config.exs
apps/indexer/lib/indexer/prometheus/celo_telemetry_instrumenter.ex
apps/indexer/lib/indexer/prometheus/setup.ex

Collects and exposes prometheus metrics around ingestion of blockchain primitives. 
* WIP feature to define metrics within a config file
* This is functional for counter, histogram and summary prometheus metric types
* Gauge still needs to be added
* Ran locally and saw metrics exposed
* Deployed to rc1staging and metrics were exposed
* wip dashboard at https://clabs.grafana.net/d/9ykNWy4Vk/blockscout-editable-copy?orgId=1
- Relates to https://github.com/celo-org/data-services/issues/431=

Define prometheus metrics in config + collect ingestion metrics

---

apps/explorer/lib/explorer/chain/celo/celo_election_rewards.ex

Previously for aggregated epoch data we were not including rewards with amount = 0. Because it is actually a valid scenario (for example where group commission = 0) we will start including those.
Tested locally to verify the query works fine.
- Relates to https://github.com/celo-org/data-services/issues/499
- Fixes https://github.com/celo-org/data-services/issues/511

Fix aggregated group and validator counts

---

apps/block_scout_web/lib/block_scout_web/etherscan.ex
apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
apps/explorer/lib/explorer/etherscan.ex
apps/explorer/test/explorer/etherscan_test.exs

Adds `blockNumber` field to the response of the `module=account&action=tokenlist` API method.
Tests updated.
- Fixes https://github.com/celo-org/data-services/issues/510

Added block number to the tokenlist response

---

apps/explorer/lib/explorer/token/instance_metadata_retriever.ex

This PR change log level for failed token instance fetching to give us more visibility over what's happening.

Change log level for failed token instance fetching

---

apps/explorer/priv/repo/migrations/20221020131800_smart_contracts_remove_md5.exs

Code is removed in this https://github.com/celo-org/blockscout/pull/790. This migration should run after the new version of the code is deployed.
No.
Locally.

Remove md5 column from smart_contract

---

apps/explorer/config/test.exs
apps/indexer/config/config.exs
apps/indexer/config/test.exs
apps/indexer/lib/indexer/block/fetcher.ex
apps/indexer/lib/indexer/fetcher/internal_transaction.ex
apps/indexer/lib/indexer/fetcher/token_balance.ex
apps/indexer/test/indexer/block/fetcher_test.exs
apps/indexer/test/indexer/fetcher/internal_transaction_test.exs

It looks like we have been fetching celo token balances for all addresses found within a block. This should obviously only be done for addresses affected by a celo transfer. This PR stops that + a lot of smaller changes.
* Documents the block fetching process with comments explaining each step 
* Removes some conditional `gold_token_enabled` functionality
* For celo this is always, and must always be enabled
* Disable min missing block process for tests
* Adjust tests to fit new behavior
* Mostly making less rpc calls during the test flow
* Ran test suite
- Fixes https://github.com/celo-org/data-services/issues/455

Stop fetching celo token balances for all addresses in block

---

apps/block_scout_web/lib/block_scout_web/templates/address_epoch_transaction/index.html.eex
apps/block_scout_web/lib/block_scout_web/templates/epoch_transaction/_election_tile.html.eex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po

Epoch transactions were not loading due to malformed HTML. Also by removing `data-async-load` attribute from the container we can avoid making duplicate initial calls.
Fixes https://github.com/celo-org/data-services/issues/539

Loading epoch transactions for an address does not finish

---

bin/remote_iex.sh

A bash script that allows for connection to a remote blockscout pod using iex. 
```
❯ ./remote_iex.sh -help
Usage: ./remote_iex.sh <environment_name> <pod (api|web|indexer)> <suffix (optional)>
Create a remote shell connection to a running blockscout pod. Assumes that the appropriate k8s context is active. Will connect
to the first matching pod when multiple exist, which may not be what you want.
Examples:
./remote_iex.sh alfajores indexer 3
./remote_iex.sh rc1staging web
./remote_iex.sh rc1 indexer 1
❯ ./remote_iex.sh rc1staging indexer
Looking for pod on gke_celo-testnet-production_us-west1-a_rc1staging cluster in namespace rc1staging
Found matching pod: pod/rc1staging-blockscout-indexer-679b6dff7f-rgdr9
Cluster IP: 10.0.2.3
Got cookie
Connecting to …
```

Remote connection script

---

apps/explorer/config/config.exs

When `ENABLE_EVENT_STREAM` is set to `"false"`, it still gets enabled and since `BEANSTALKD_HOST` and `BEANSTALKD_PORT` are missing, the indexer fails with
```
{"error":{"initial_call":null,"reason":"** (MatchError) no match of right hand side value: :error
(explorer 0.0.1) lib/explorer/celo/events/contract_event_stream.ex:45: Explorer.Celo.Events.ContractEventStream.handle_continue/2
(stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
(stdlib 3.17) gen_server.erl:437: :gen_server.loop/7
(stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
"},"logging.googleapis.com/sourceLocation":{"file":"gen_server.erl","line":949,"function":"gen_server.error_info/7"},"message":"GenServer Explorer.Celo.Events.ContractEventStream terminating
** (MatchError) no match of right hand side …
```

Fixed incorrectly parsed flag when event stream is disabled

---

apps/block_scout_web/lib/block_scout_web/chain.ex
apps/block_scout_web/lib/block_scout_web/templates/epoch_transaction/_election_tile.html.eex
apps/block_scout_web/lib/block_scout_web/views/api/rpc/reward_view.ex
apps/block_scout_web/lib/block_scout_web/views/epoch_transaction_view.ex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
apps/explorer/lib/explorer/chain/celo/celo_election_rewards.ex
apps/explorer/test/explorer/chain/celo_election_rewards_test.exs

Address epoch transaction page were loading quite slow because of numerous queries made to `addresses` table, this PR adds preloading of those in a single query.
- Fixes https://github.com/celo-org/data-services/issues/580

Fix performance issues while loading address epoch transactions

---

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/stats_controller.ex
apps/block_scout_web/test/block_scout_web/controllers/api/rpc/stats_controller_test.exs

If the `cmc` param is passed to the `tokensupply` method of the api, the result will be returned as `text/plain` instead of json as required by coinmarketcap's system. 
e.g.
* http://localhost:4011/api?module=stats&action=tokensupply&contractaddress=0xd8763cba276a3738e6de85b4b3bf5fded6d6ca73
* works as before, returns json
* http://localhost:4011/api?module=stats&action=tokensupply&contractaddress=0xd8763cba276a3738e6de85b4b3bf5fded6d6ca73&cmc=true
* returns only the value as text ( no string quotes or javascript object wrapper )
* tested locally
* added unit test
- Fixes https://github.com/celo-org/data-services/issues/585

CoinMarketCap api for tokensupply endpoint

---

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/stats_controller.ex
apps/block_scout_web/test/block_scout_web/controllers/api/rpc/stats_controller_test.exs

Formats the output of the tokensupply rpc call to be in "eth" rather than wei, as per the request of Coin Market Cap
* Modified and passed unit tests
- Fixes https://github.com/celo-org/data-services/issues/594

Format output of CMC api to be in "eth" rather than wei

---

apps/explorer/priv/repo/migrations/20221214162647_lock_stats_table.exs

Prevents deadlocks on `celo_transaction_stats` table by having the update procedure lock the table in `EXCLUSIVE` mode  (read only, writes only for the tx with the lock, only `ACCESS EXCLUSIVE` is higher lock) for the duration of the update. 
> Unable to reproduce this locally....
* Tested on rc1staging
* Deactivate indexer for an hour to build up backlog
* Restart to assert deadlocks happen
* Deactivate again
* Apply migration
* Restart and notice no more deadlocks
- Fixes https://github.com/celo-org/data-services/issues/554
- Fixes https://github.com/celo-org/data-services/issues/326
- Fixes https://github.com/celo-org/data-services/issues/411

Add lock to celo_transaction_stats table before update.

---

apps/block_scout_web/assets/js/lib/smart_contract/interact.js
apps/explorer/lib/explorer/celo/account_reader.ex
apps/explorer/lib/explorer/celo/contract_cache/address_cache.ex

The warning modal is displaying an error for an invalid access due to the sanctioned address test not working when no address is provided. This adds a simple test for the existence of the address before checking if it's sanctioned.
* Fixes some warnings that prevent compilation
* Tested locally
* Can correctly send a transaction via updated javascript
- Fixes https://github.com/celo-org/data-services/issues/604

Fix error message on write contract page

---

apps/block_scout_web/assets/css/components/_label.scss
apps/block_scout_web/lib/block_scout_web/models/get_address_tags.ex
apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
apps/explorer/lib/explorer/tags/address_tag_cataloger.ex
apps/explorer/lib/mix/tasks/list_events.ex
apps/explorer/priv/repo/migrations/20230109155142_populate_tags_table.exs
apps/indexer/lib/indexer/memory/monitor.ex

Displays tags as little "pillow" elements next to the address on the Address Details page.
Validator-related tags get updated every hour.
Minor formatting and warning fixes. Removes unused tags functionality.
Tested on staging.
- Fixes https://github.com/celo-org/data-services/issues/607.

Display address tags

---

apps/ethereum_jsonrpc/priv/js/tokens/celoTokens.json

Adds a "datasource" for known tokens (used to display total tokens value), see an example [here](https://github.com/celo-org/blockscout/blob/master/apps/explorer/lib/explorer/known_tokens/source/my_ether_wallet.ex#L12). Will be referenced in a subsequent PR.
No.
Locally.
- Relates to https://github.com/celo-org/data-services/issues/610.

Added list of known tokens

---

apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
apps/explorer/lib/explorer/chain.ex

Adds a link `View in Celo Safe App` to the address details page for `GnosisSafeProxy` contracts.
Updates the detection logic for that from master copy to singleton according to the latest implementation of the [proxy contract](https://github.com/safe-global/safe-contracts/blob/main/contracts/proxies/GnosisSafeProxy.sol#L20).
Also supports Alfajores.
The link leads to https://safe.celo.org/mainnet:0x89C097aDffb38644af11E6246B7cd13e1E287e64/transactions/history
Adds a convenience function mapping chain ids to Celo chain names.
- Fixes https://github.com/celo-org/data-services/issues/608

Added support for Celo Safe contracts

---

apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
apps/block_scout_web/lib/block_scout_web/views/address_view.ex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
apps/explorer/config/config.exs
apps/indexer/lib/indexer/fetcher/internal_transaction.ex

It does three things:
- disables the address tag cataloger for pods working with replicas
- updates concurrency settings for internal TXs
- removed the word "Contract" from the address details label in favor of tags `EOA` / `contract`

Small fixes

---

apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs
apps/explorer/lib/explorer/repo.ex
apps/explorer/mix.exs
mix.lock

Adds a module (RemoteRepo) which forwards all ecto queries to a primary db instance for execution. This can be used by simply referencing Explorer.RemoteRepo in almost any place where Repo is used.
* Updated underlying fly_postgres_elixir lib (in other repo)
* Ignored flaky test around celo banner
* Passed test suite
* Deployed to rc1staging and tested 
Here we connect to a web pod which only has a direct connection to a replica db and forward an arbitrary `query` call to the indexer pod for execution against a master (write enabled) db. We then use the local (replica) db connection to retrieve the value.
```
❯ ./remote_iex.sh rc1staging web
Looking for pod on gke_celo-testnet-production_us-west1-a_rc1staging cluster in namespace rc1staging
Found matching pod: …
```

Create remote repo.

---

apps/block_scout_web/config/config.exs
apps/block_scout_web/lib/block_scout_web/application.ex
apps/block_scout_web/lib/block_scout_web/celo/metrics_cron.ex
apps/explorer/lib/explorer/celo/metrics/database_metrics.ex
apps/explorer/lib/explorer/celo/telemetry/instrumentation/third_party/database.ex
apps/explorer/lib/explorer/chain/events/pubsub_source.ex
apps/indexer/lib/indexer/celo/metrics_cron.ex
apps/indexer/lib/indexer/celo/telemetry/instrumentation/indexer.ex
apps/indexer/lib/indexer/fetcher/empty_blocks_sanitizer.ex
apps/indexer/lib/indexer/pending_transactions_sanitizer.ex

Adds more metrics to the indexer + web + api apps, specifically:
* Add database stats to web and api pods
* This gives us insight into replica db behavior
* Expose the top 10 database tables by size
* Expose internal transaction fetcher concurrency values 
* Functionality exists to add other fetchers
* Expose empty block + pending transaction sanitizer invocation count
* Add periodic measurement functionality to blockscoutweb (web + api pods)
* Minor refactoring of metric labels
* `indexer_db_locks` etc no longer valid name, as this is measured from different apps
* Passed test suite
* Deployed to rc1staging and viewed metrics directly on prometheus endpoint
- Closes https://github.com/celo-org/data-services/issues/633

Add more metrics to the app

---

apps/block_scout_web/lib/block_scout_web/controllers/csv_export_controller.ex
apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex
config/runtime/dev.exs
config/runtime/prod.exs
config/runtime/test.exs

Based on discoveries by @shazarre and @carterqw2 it seems that long running internal transaction export queries (in this instance, 15 hours long) are causing locks to build up on the master database and preventing data from being inserted.
This pr disables internal transaction csv export by default, with an optional environment var override to enable.
* Deployed to rc1staging
* csv export link is removed
* directly hitting itx export link results in 404
- Fixes https://github.com/celo-org/data-services/issues/639

Conditionally disable itx csv export

---

apps/block_scout_web/lib/block_scout_web/application.ex
apps/explorer/lib/explorer/celo/telemetry/instrumentation/api.ex

This PR exposes metrics for absinthe operation times.
Tested locally and in production.
- Relates to https://github.com/celo-org/data-services/issues/631

Expose GraphQL resolution metrics

---

apps/explorer/lib/explorer/token/instance_metadata_retriever.ex
apps/explorer/test/explorer/token/instance_metadata_retriever_test.exs

Fixes case where `tokenURI` method of ERC-721 returns data url with base64 encoded JSON.
Tested on staging.
- Fixes https://github.com/celo-org/data-services/issues/656

Add base64 encoded JSON support while fetching NFTs

---

apps/indexer/lib/indexer/fetcher/token_instance.ex

This PR enables polling once a day for `token_instance` fetcher.
No real need to be tested.
- Relates to https://github.com/celo-org/data-services/issues/671

Enable token_instance fetcher polling

---

apps/event_stream/lib/event_stream/publishers/publisher.ex

Fix an error where the publisher instance is not configurable in production environment due to compile time config.
None
Tested on rc1staging and saw beanstalkd connection attempts
- Relates to https://github.com/celo-org/data-services/issues/653

Don't use compile_env for value that changes at runtime.

---

apps/explorer/lib/explorer/chain/token/instance.ex
apps/indexer/lib/indexer/fetcher/token_instance.ex

This PR fixes typo in telemetry event connected to NFT ingestion errors resulting in metrics not being available.

Fix NFT metrics event typo

---

.github/workflows/helm_deploy_dispatch.yml
apps/block_scout_web/.iex.exs
apps/block_scout_web/lib/block_scout_web/controllers/verified_contracts_controller.ex
apps/block_scout_web/lib/block_scout_web/resolvers/token_transfer_tx.ex
apps/block_scout_web/lib/block_scout_web/templates/verified_contracts/_stats.html.eex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
apps/block_scout_web/test/block_scout_web/controllers/verified_contracts_controller_test.exs
apps/explorer/lib/explorer/application.ex
apps/explorer/lib/explorer/chain.ex
apps/explorer/lib/explorer/chain/smart_contract.ex
apps/explorer/lib/explorer/graphql.ex
apps/explorer/test/explorer/chain/cache/new_contracts_counter_test.exs
apps/explorer/test/explorer/chain/smart_contract_test.exs
apps/explorer/test/support/factory.ex

A collection of patches to resolve issues that have occurred since the last upstream merge and deployment.
`NewContractsCounter` runs an expensive query whenever a pod is started + every 30 minutes. This should be very cheap via an index on the transactions table, but the query plan does not use it. Instead this feature is just disabled and new contract count is no longer shown
* Custom graphql queries became very expensive due to db changes, the optimised replacement query lacked pagination support - this has been readded
* Support for token_id within the token_transfer response has been readded, and backwards compatibility from lists of token ids
* A single transfer can presumably include multiple token_ids, but it's unclear to what extent this feature is used / supported in external …

Resolve Blockscout live issues

---

helm/values/values-rc1-blockscout1.yaml
helm/values/values-rc1-blockscout3.yaml

Description
Increase the resource.request for web containers in rc1 environments. To illustrate the reasoning, these are the graphs for the container ratios (resource requested / resource usage):

Increase resources for blockscout web pods in rc1

---

apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
apps/explorer/lib/explorer/chain/import.ex
apps/explorer/test/explorer/chain/import_test.exs
apps/indexer/test/indexer/fetcher/coin_balance_on_demand_test.exs

Deactivates broadcasting information from indexer to web / api pods via erlang clustering. 
Currently the handling of messages triggers db calls, which has exacerbated db contention in times of high blockchain activity. Additionally the real time update mechanism has never been compatible with the concept of replica db lag. 
Disabling this prevents user confusion + reduces the amount of db calls made by web & api pods.
* Disables some tests that explicitly assert event broadcast
* Already running on baklava during load test
- Fixes https://github.com/celo-org/data-services/issues/721

Don't broadcast messages on import.

---

.github/workflows/blockscout.yml
.github/workflows/codeql-analysis.yml
apps/explorer/config/test.exs
config/test.exs

Refactor GitHub general workflow:
* Renamed the workflow file from `config.yml` to `blockscout.yml`
* Added a `run-name` property to show the reference (branch) in the name of the execution (for easy identification of it from `Actions` tab)
* Running on self-hosted org runners
* Specify the container to run at job level

Not so small refactor general workflow

---

apps/block_scout_web/lib/block_scout_web/templates/tokens/instance/overview/_details.html.eex
apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
apps/block_scout_web/test/block_scout_web/views/tokens/instance/overview_view_test.exs

Patches the `external_url` method in `apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex` to only consider urls that begin with `http` as valid. This allows both "http" and "https" external urls to be rendered within the page and treats any other uri as missing.
This is needed to prevent a reported XSS exploit whereby an NFT encoded a `javascript:eval('blah')` within the `external_url` content of it's own metadata.
Minor whitespace changes
* Tested locally against alfajores db
* Developed unit test for this case
* Passed test suite
- Relates to https://github.com/celo-org/data-services/issues/733

Patch external_url method to constrain set of valid uris

---

apps/block_scout_web/lib/block_scout_web/controllers/address_read_proxy_controller.ex

The application is crashing when trying to display data it has not loaded from the database (specifically celo epoch data). This PR adds an optional preload to the db fetch to include `celo_accounts` information should it exist for the `address` being fetched.
* tested locally against rc11 db
* http://localhost:4011/address/0x4aAD04D41FD7fd495503731C5a2579e19054C432/read-proxy#address-tabs loads correctly without 500 error
- Fixes https://github.com/celo-org/data-services/issues/734

Preload `celo_account` on AddressReadProxyController when available.

---

.dockerignore
.gitignore

Testing a dockerignore file to make sure it ignores the gha credentials.

adding a dockerignore file to ignore gha-credentials

---

apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
apps/explorer/lib/explorer/chain/import/runner/address/token_balances.ex
apps/explorer/lib/explorer/chain/token.ex
apps/explorer/priv/repo/migrations/20240207100347_recommended_tx_index.exs
apps/indexer/test/indexer/fetcher/celo/celo_epoch_data_test.exs

Forces an "unknown" gas currency to be reindexed as a token by the indexer. This allows for arbitrary gas currencies to be displayed without being explicitly whitelisted.
* Running on alfajores and displaying custom currency
* https://explorer.celo.org/alfajores/tx/0x4d658f065705a57ec088c4cb56158d41353d187aa7dad32a2eb4a4d15053a5f2
* adds a recommended index to the transactions table
* recommended by pghero to increase indexer performance 
* skips a flaky test

Queue unknown gas currency for token indexing.

---

apps/block_scout_web/config/navigation.exs

Missed a link that security wanted removed
_Describe any minor or "drive-by" changes here._
_An explanation of how the changes were tested or an explanation as to why they don't need to be._
_Add any artifacts (links, screenshots) you can include to increase the reviewers' confidence in the change._
- Relates to #[issue number here]
- Fixes #[issue number here]

Remove trellis.

---

apps/block_scout_web/config/navigation.exs
apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po

- Spelling `Derivates` -> `Derivatives`
- Remove `ImmortalDAO` from defi list (replaced in new section by ImmortalX)

Fix spelling. Remove moved link

---

apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
apps/explorer/lib/explorer/celo/util.ex
apps/explorer/lib/explorer/etherscan.ex

The `txlist` RPC endpoint uses the `CeloParams` table to fetch names of stable tokens used as gas currencies. The way the `feeCurrency` mapping is implemented is a bit cumbersome and requires manual population of the table with the parameters. It can take it from the `Tokens` table instead.
Before:
```
curl -s https://explorer.celo.org/mainnet/api\?module\=account\&action\=txlist\&address\=0xccc9576F841de93Cd32bEe7B98fE8B9BD3070e3D | jq '.' | grep -i "0xcb625dd58eb29e8df606276927375ea8aa9c983cb09812aa5784b5da28d6e149" -A 10 -B 10 | grep feeCurrency
"feeCurrency": "CELO",
```
After:
```
curl -s https://explorer.celo.org/mainnet/api\?module\=account\&action\=txlist\&address\=0xccc9576F841de93Cd32bEe7B98fE8B9BD3070e3D | jq '.' | grep -i …
```

Fix txlist RPC endpoint to use the token info for fee currencies
